// 프렌즈 시즌1 에피소드 모티브 운세 데이터
// fortunes 항목 형식: [등급(1~5 커피잔), 한국어 운세, English fortune, { who, en: 실제 대사, ko: 번역 }]
// 대사 출처: https://edersoncorbari.github.io/friends-scripts/season/0101.html ~ 0124.html

window.EPISODES = [
  {
    code: "S01E01", title: "The One Where Monica Gets a Roommate",
    moment: { ko: "웨딩드레스 차림으로 카페에 뛰어든 날", en: "The day a runaway bride burst into the café" },
    lucky: { ko: "커피 한 잔", en: "A cup of coffee" },
    fortunes: [
      [5, "작은 성공 하나가 큰 자신감의 씨앗이 되는 날이에요. 오늘 해낸 사소한 일을 꼭 칭찬해 주세요.", "A small win plants the seed of big confidence today. Be sure to praise yourself for the little thing you pulled off.",
        { who: { en: "Rachel", ko: "레이첼" }, en: "I figure if I can make coffee, there isn't anything I can't do.", ko: "커피도 만들 줄 알게 됐으니, 이제 못 할 게 없을 것 같아." }],
      [5, "곁에서 믿어주는 목소리가 등을 힘껏 밀어줄 거예요. 망설이던 일에 오늘 첫발을 내디뎌 보세요.", "A voice that believes in you will give you a strong push. Take the first step on what you've been hesitating over.",
        { who: { en: "Ross", ko: "로스" }, en: "Come on, you made coffee! You can do anything!", ko: "자, 커피도 만들었잖아! 넌 뭐든 할 수 있어!" }],
      [4, "처음엔 버겁게 느껴지는 새 환경이 곧 당신의 무대가 돼요. 불편함 속에 숨은 재미를 찾아보세요.", "The new world that feels rough at first will soon become your stage. Look for the fun hiding inside the discomfort.",
        { who: { en: "Monica", ko: "모니카" }, en: "Welcome to the real world! It sucks. You're gonna love it!", ko: "현실 세계에 온 걸 환영해! 끔찍하지. 근데 너도 좋아하게 될 거야!" }],
      [4, "기분을 끌어올려 줄 작은 선물을 스스로에게 해도 좋은 날이에요. 단, 영수증은 잘 챙겨두세요.", "A good day to treat yourself to something that lifts your mood. Just hold on to the receipt.",
        { who: { en: "Rachel", ko: "레이첼" }, en: "They're my new 'I don't need a job, I don't need my parents, I've got great boots' boots!", ko: "이건 내 새 '일도 필요 없고 부모님도 필요 없어, 멋진 부츠가 있으니까' 부츠야!" }],
      [3, "마음이 요동칠 땐 깊은 숨 세 번이면 충분해요. 오늘은 서두르지 않는 쪽이 이겨요.", "When your heart races, three deep breaths are enough. Today, the unhurried side wins.",
        { who: { en: "Monica", ko: "모니카" }, en: "Just breathe, breathe.. that's it. Just try to think of nice calm things...", ko: "숨 쉬어, 천천히... 그렇지. 기분 좋고 차분한 것만 생각해 봐..." }],
      [3, "오늘 내뱉은 말은 돌고 돌아 당신에게 돌아와요. 미움 대신 다정한 말을 골라보세요.", "The words you send out today will circle back to you. Choose kind ones over bitter ones.",
        { who: { en: "Phoebe", ko: "피비" }, en: "Don't hate, you don't want to put that out into the universe.", ko: "미워하지 마, 그런 걸 우주에 내보내면 안 돼." }],
      [2, "일이 의미 없게 느껴지는 날이에요. 작은 일이라도 누군가에겐 차이를 만든다는 걸 기억하세요.", "Work may feel pointless today. Remember that even small tasks make a difference to someone.",
        { who: { en: "Chandler", ko: "챈들러" }, en: "If I don't input those numbers,... it doesn't make much of a difference...", ko: "내가 그 숫자들을 입력 안 해도... 별 차이는 없지만..." }],
      [1, "작은 불길한 신호들이 눈에 밟히는 날이에요. 너무 의미 부여하지 말고 오늘은 조심조심 지나가요.", "Little bad omens may catch your eye today. Don't read too much into them, just tread carefully.",
        { who: { en: "Phoebe", ko: "피비" }, en: "I just pulled out four eyelashes. That can't be good.", ko: "방금 속눈썹이 네 개나 빠졌어. 좋은 징조는 아니겠지." }],
      [1, "오늘은 거절이 여러 번 찾아올 수 있어요. 하지만 열두 번의 '아니오' 뒤에 첫 '예'가 기다리고 있어요.", "Rejection may knock more than once today. But a first 'yes' is waiting behind those twelve 'no's.",
        { who: { en: "Rachel", ko: "레이첼" }, en: "I'm trained for nothing! I was laughed out of twelve interviews today.", ko: "난 할 줄 아는 게 없어! 오늘 면접 열두 군데에서 비웃음만 샀다고." }],
    ],
  },
  {
    code: "S01E02", title: "The One with the Sonogram at the End",
    moment: { ko: "라자냐 속에 반지가 사라지고, 초음파 사진을 처음 본 날", en: "A ring lost in lasagna, and a first sonogram" },
    lucky: { ko: "라자냐", en: "Lasagna" },
    fortunes: [
      [5, "피할 수 없는 큰 변화가 축복으로 다가오고 있어요. 새로운 역할을 기꺼이 받아들여 보세요.", "A big change you can't avoid is arriving as a blessing. Embrace your new role with open arms.",
        { who: { en: "Ross", ko: "로스" }, en: "No matter what I do, though, I'm still gonna be a father.", ko: "내가 뭘 하든, 난 아빠가 되는 거야." }],
      [4, "첫인상이 많은 걸 말해주는 날이에요. 처음 느낀 설렘을 믿어보세요.", "First impressions speak volumes today. Trust the flutter you felt at the start.",
        { who: { en: "Rachel", ko: "레이첼" }, en: "Everything you need to know is in that first kiss.", ko: "알아야 할 건 전부 첫 키스에 담겨 있어." }],
      [4, "차근차근 하는 사람이 결국 해내는 날이에요. 속도보다 꼼꼼함에 운이 따라요.", "Steady hands get it done today. Luck favors thoroughness over speed.",
        { who: { en: "Ross", ko: "로스" }, en: "They know what they're doing, they take their time, they get the job done.", ko: "다들 뭘 하는지 알고, 서두르지 않고, 일을 확실히 끝내." }],
      [3, "지금 서 있는 자리를 솔직하게 인정하면 오히려 마음이 가벼워져요. 언젠가 ‘내 가게’가 될 날을 향해 한 걸음씩 가요.", "Owning up to where you stand now will lighten your heart. Step by step toward the day it's truly yours.",
        { who: { en: "Monica", ko: "모니카" }, en: "No Mom, I don't have a restaurant, I work in a restaurant.", ko: "아니 엄마, 내가 식당을 가진 게 아니라 식당에서 일하는 거라고." }],
      [3, "사소한 걱정이 더 큰 그림 앞에서 작아지는 날이에요. 신경 쓰이던 일은 잠시 내려놓아도 괜찮아요.", "Small worries shrink in front of the bigger picture today. It's fine to set aside what's been nagging you.",
        { who: { en: "Chandler", ko: "챈들러" }, en: "Kinda puts that whole pillow thing in perspective, huh, Mon?", ko: "베개 따위는 별거 아니게 느껴지지, 모니카?" }],
      [2, "오늘은 모두가 감동하는 것이 당신 눈엔 감자로 보일 수도 있어요. 보는 각도를 한 번 바꿔보세요.", "What moves everyone else may look like a potato to you today. Try tilting your point of view.",
        { who: { en: "Phoebe", ko: "피비" }, en: "You know, if you tilt your head to the left, and relax your eyes, it kinda looks like an old potato.", ko: "고개를 왼쪽으로 기울이고 눈에 힘을 빼면, 좀 오래된 감자처럼 보여." }],
      [2, "익숙함을 행복으로 착각하고 있진 않은지 돌아볼 때예요. 조금 아프더라도 솔직한 답이 앞으로 나아가게 해줘요.", "Check whether you've mistaken comfort for happiness. An honest answer, even a painful one, moves you forward.",
        { who: { en: "Barry", ko: "배리" }, en: "I thought we were happy. We weren't happy.", ko: "우린 행복한 줄 알았어. 근데 아니었지." }],
      [1, "오늘 계획 하나쯤은 틀어질 수 있어요. 망친 건 망친 대로 두고 다음 끼니를 기약해요.", "One plan might fall apart today. Let what's ruined stay ruined and look forward to the next meal.",
        { who: { en: "Joey", ko: "조이" }, en: "Well, this is still ruined, right?", ko: "음, 이건 여전히 망친 거지, 그치?" }],
    ],
  },
  {
    code: "S01E03", title: "The One with the Thumb",
    moment: { ko: "탄산음료 캔에서 뜻밖의 것이 나오고, 공돈이 굴러든 날", en: "Something odd in a soda can, and money out of nowhere" },
    lucky: { ko: "탄산음료 캔", en: "A soda can" },
    fortunes: [
      [5, "뜻밖의 곳에서 재물운이 굴러들어오는 날이에요. 이상한 일이 생겨도 일단 웃고 봐요.", "Money may roll in from the strangest place today. Even if something weird happens, smile first.",
        { who: { en: "Phoebe", ko: "피비" }, en: "Y'know, those stupid soda people gave me seven thousand dollars for the thumb.", ko: "있잖아, 그 멍청한 탄산음료 회사가 엄지 때문에 칠천 달러를 줬어." }],
      [5, "흩어져 있던 사람들이 하나로 뭉치는 날이에요. 오늘 함께하는 일은 뭐든 이길 거예요.", "Scattered people come together as one today. Whatever you do together, you'll win.",
        { who: { en: "Rachel", ko: "레이첼" }, en: "I mean, it-it was like, it was like he made us into a team.", ko: "그러니까, 그 사람이 우릴 한 팀으로 만들어 준 것 같았어." }],
      [4, "관점만 살짝 바꾸면 고민이 즐거움으로 변해요. 단, 지갑은 양심과 상의해서 여세요.", "A slight shift in view turns worry into fun. Just check with your conscience before opening your wallet.",
        { who: { en: "Rachel", ko: "레이첼" }, en: "Yeah, but if you spent it, it would be like shopping!", ko: "응, 근데 그걸 쓰면 쇼핑하는 거잖아!" }],
      [4, "머리보다 마음이 정답을 알고 있는 날이에요. 설렘이 없다면 솔직해져도 괜찮아요.", "Your heart knows the answer better than your head today. If there's no spark, it's okay to be honest.",
        { who: { en: "Paula", ko: "폴라" }, en: "Honey.. you should always feel the thing.", ko: "자기야... 언제나 그 '느낌'이 있어야 해." }],
      [3, "변화를 억지로 붙잡지 않아도 되는 날이에요. 달라진 마음을 있는 그대로 인정해 보세요.", "You don't need to hold back change today. Accept your shifting feelings as they are.",
        { who: { en: "Monica", ko: "모니카" }, en: "Things change. People change.", ko: "상황은 변해. 사람도 변하고." }],
      [2, "아쉬운 이별이 있을 수 있지만 금방 회복돼요. 오늘은 스스로에게 시간을 넉넉히 주세요.", "A goodbye may sting a little, but you'll bounce back. Give yourself plenty of time today.",
        { who: { en: "Ross", ko: "로스" }, en: "Hey hey, we'll be fine. We're just gonna need a little time.", ko: "에이, 우린 괜찮을 거야. 그냥 시간이 좀 필요할 뿐이야." }],
      [2, "몸이 보내는 신호에 귀 기울여야 할 때예요. 오늘은 나쁜 습관 하나를 쉬게 해주세요.", "Time to listen to what your body is telling you. Give one bad habit a day off.",
        { who: { en: "Joey", ko: "조이" }, en: "Do you have any respect for your body?", ko: "넌 네 몸을 좀 아낄 생각이 없냐?" }],
      [1, "유혹에 무너지기 쉬운 날이에요. 약한 순간이 와도 한 번만 더 버텨 보세요, 그걸로 충분해요.", "Temptation hits hard today. When the weak moment comes, hold out just once more, that's enough.",
        { who: { en: "Chandler", ko: "챈들러" }, en: "I don't care, I don't care! Game's over! I'm weak!", ko: "몰라, 몰라! 게임 끝났어! 난 약해!" }],
    ],
  },
  {
    code: "S01E04", title: "The One with George Stephanopoulos",
    moment: { ko: "하키 경기장의 소동과 잘못 배달된 피자의 밤", en: "Chaos at a hockey game and a misdelivered pizza" },
    lucky: { ko: "피자", en: "Pizza" },
    fortunes: [
      [5, "스스로 이룬 성과가 이름표를 달고 찾아와요. 오늘은 자신에게 반갑게 인사해 주세요.", "Something you earned yourself arrives with your name on it. Say a warm hello to yourself today.",
        { who: { en: "Rachel", ko: "레이첼" }, en: "Look-look-look-look-look, my first pay check! Look at the window, there's my name! Hi, me!", ko: "봐봐봐봐봐, 내 첫 월급! 봉투 창에 내 이름 있어! 안녕, 나!" }],
      [5, "평범해 보이던 것 속에 마법이 숨어 있어요. 오늘 손에 쥔 기회를 소중히 심어보세요.", "There's magic hidden in what looked ordinary. Plant the chance in your hand with care today.",
        { who: { en: "Rachel", ko: "레이첼" }, en: "I've got magic beans.", ko: "나한테 마법의 콩이 있어." }],
      [4, "홀로서기가 생각보다 잘 되고 있어요. 스스로를 조금 더 자랑스러워해도 좋아요.", "Standing on your own is going better than you think. You're allowed to be a little prouder.",
        { who: { en: "Monica", ko: "모니카" }, en: "You should feel great about yourself! You're doing this amazing independence thing!", ko: "너 자신을 대견하게 여겨야 해! 이렇게 멋지게 독립하고 있잖아!" }],
      [4, "작은 기회를 큰 기회로 키우는 재치가 빛나는 날이에요. 한 번의 찬스를 오래 가는 무언가로 바꿔보세요.", "Your wit turns small chances into big ones today. Make one lucky break into something that lasts.",
        { who: { en: "Chandler", ko: "챈들러" }, en: "If I were omnipotent for a day, I'd.. make myself omnipotent forever.", ko: "내가 하루 동안 전지전능하다면... 나를 영원히 전지전능하게 만들 거야." }],
      [3, "거창한 이유 없이도 곁에 있어주는 친구가 있어요. 오늘은 그 마음을 그냥 받아들여 보세요.", "There are friends who show up for you with no big reason. Just accept their love today.",
        { who: { en: "Joey", ko: "조이" }, en: "We love you, man.", ko: "우리가 널 사랑하잖아, 친구." }],
      [2, "선택이 아쉽게 느껴질 수 있는 날이에요. 후회는 짧게, 다음 계획은 신중하게 세워요.", "A choice may feel like a letdown today. Keep the regret short and plan the next one with care.",
        { who: { en: "Joey", ko: "조이" }, en: "Whoah, boy, hockey was a big mistake! There was a whole bunch of stuff we could've done tonight!", ko: "워, 하키는 큰 실수였어! 오늘 밤 할 수 있는 게 잔뜩 있었는데!" }],
      [2, "남의 선택에 끌려가 불편한 자세로 버틸 수 있어요. 다음엔 원하는 걸 먼저 말해보세요.", "You may end up stuck in someone else's plan today. Next time, say what you want first.",
        { who: { en: "Monica", ko: "모니카" }, en: "Could've played Monopoly, but nooooo.", ko: "모노폴리나 할 수 있었는데, 아니지이이." }],
      [1, "앞이 막막하게 느껴지는 날이에요. 거창한 계획 대신 오늘 할 일 하나만 정해도 충분해요.", "The road ahead may feel blank today. Instead of a grand plan, just decide on one thing to do.",
        { who: { en: "Phoebe", ko: "피비" }, en: "I don't even have a 'pl'.", ko: "난 '계'도 없어. 계획의 '계'자도." }],
      [1, "날아오는 퍽을 조심해야 하는 날이에요. 뜻밖의 충격이 있어도 결국 웃으며 이야기하게 될 거예요.", "Watch out for flying pucks today. Even if something hits you out of nowhere, you'll laugh about it later.",
        { who: { en: "Ross", ko: "로스" }, en: "I'm in a lot of pain here, alright? My face is dented.", ko: "나 지금 엄청 아프거든? 얼굴이 찌그러졌다고." }],
    ],
  },
  {
    code: "S01E05", title: "The One with the East German Laundry Detergent",
    moment: { ko: "빨래방에서 처음 빨래를 배우던 날", en: "A first lesson at the laundromat" },
    lucky: { ko: "세탁 세제", en: "Laundry detergent" },
    fortunes: [
      [5, "당신 몫을 당당히 지켜낼 용기가 넘치는 날이에요. 오늘은 물러서지 말고 한 발 앞으로 나가세요.", "You're brimming with courage to stand up for what's yours. Don't back down today, step forward.",
        { who: { en: "Rachel", ko: "레이첼" }, en: "If you want this cart, you're gonna have to take me with it!", ko: "이 카트 갖고 싶으면, 나까지 데려가야 할 거야!" }],
      [5, "어제와 다른 새로운 당신이 박수를 받는 날이에요. 변화한 모습을 마음껏 뽐내세요.", "A brand-new you gets a round of applause today. Show off how much you've grown.",
        { who: { en: "Ross", ko: "로스" }, en: "You were incredible! Brand new woman, ladies and gentlemen.", ko: "너 정말 끝내줬어! 신사 숙녀 여러분, 완전히 새로운 여성입니다." }],
      [4, "힘든 일도 함께하는 사람이 있으면 절반이 돼요. 오늘은 든든한 동지가 곁에 있어요.", "Hard things shrink by half with someone beside you. A trusty partner is with you today.",
        { who: { en: "Chandler", ko: "챈들러" }, en: "We should always always break up together.", ko: "우리 헤어질 땐 항상, 항상 같이 하자." }],
      [3, "결과가 완벽하진 않아도 핵심은 해냈어요. 분홍빛으로 물든 부분도 오늘의 멋이라 생각해요.", "Maybe not perfect, but you nailed the main point. Think of the pink-tinted bits as today's style.",
        { who: { en: "Ross", ko: "로스" }, en: "You got the clothes clean. Now that's the important part.", ko: "옷은 깨끗해졌잖아. 그게 중요한 거야." }],
      [3, "긴장되는 순간엔 마음속 행복한 장소를 떠올려 보세요. 콧노래 한 소절이 오늘의 부적이에요.", "In tense moments, picture your happy place. A hummed tune is today's lucky charm.",
        { who: { en: "Phoebe", ko: "피비" }, en: "Go to your happy place. La la la la la la la.", ko: "네 행복한 곳으로 가. 라 라 라 라 라 라 라." }],
      [2, "미뤄둔 어려운 말을 꺼내야 할 때예요. 오늘 하면 내일은 훨씬 가벼워져요.", "It's time to say the hard thing you've been putting off. Do it today, and tomorrow will feel much lighter.",
        { who: { en: "Monica", ko: "모니카" }, en: "Nobody likes breaking up with someone. You just gotta do it.", ko: "누구도 이별을 좋아하진 않아. 그냥 해야 하는 거야." }],
      [1, "의도와 다르게 일이 꼬이는 날이에요. 최악 같아도 지나고 보면 웃긴 에피소드가 돼요.", "Things may go sideways despite your best intentions. It feels like the worst, but it'll be a funny story later.",
        { who: { en: "Chandler", ko: "챈들러" }, en: "This is the worst break-up in the history of the world.", ko: "이건 세계 역사상 최악의 이별이야." }],
      [1, "지나간 선택이 자꾸 떠오르는 날이에요. 후회에 매달리기보다 지금 곁에 있는 것을 챙기세요.", "Past choices keep replaying today. Instead of clinging to regret, take care of what's with you now.",
        { who: { en: "Joey", ko: "조이" }, en: "I made a huge mistake. I never should have broken up with her.", ko: "내가 큰 실수를 했어. 그녀랑 헤어지지 말았어야 했는데." }],
    ],
  },
  {
    code: "S01E06", title: "The One with the Butt",
    moment: { ko: "작은 배역이라도 무대에 서고 싶었던 날", en: "Taking any role just to be on stage" },
    lucky: { ko: "연극 티켓", en: "A theater ticket" },
    fortunes: [
      [5, "막이 오르고 있어요. 오늘은 기대해도 좋은, 특별한 일이 시작되는 날이에요.", "The curtain is rising. Today is a day to expect something special to begin.",
        { who: { en: "Ross", ko: "로스" }, en: "Magic is about to happen.", ko: "이제 마법이 일어날 거야." }],
      [5, "남들이 뭐라 하든 당신에겐 소중한 기회가 찾아와요. 자신 있게 붙잡으세요.", "Whatever others say, a precious chance is coming your way. Grab it with confidence.",
        { who: { en: "Joey", ko: "조이" }, en: "Make jokes, I don't care! This is a big break for me!", ko: "농담이나 해, 상관없어! 이건 나한테 큰 기회라고!" }],
      [4, "멀게만 느껴지던 사람에게 다가갈 용기가 생기는 날이에요. 먼저 인사 한마디 건네보세요.", "You'll find the courage to approach someone who seemed out of reach. Start with a simple hello.",
        { who: { en: "Rachel", ko: "레이첼" }, en: "She's a person, you can do it!", ko: "그녀도 사람이야, 넌 할 수 있어!" }],
      [4, "계획에 없던 작은 모험이 기분 좋은 이야깃거리가 돼요. 오늘은 평소와 다른 길로 가보세요.", "An unplanned little adventure becomes a great story. Take a different route today.",
        { who: { en: "Chandler", ko: "챈들러" }, en: "Once I got on the subway, right, and it was at night, and I rode it all the way to Brooklyn... just for the hell of it.", ko: "한번은 밤에 지하철을 타고, 그냥 재미로 브루클린까지 끝까지 가봤어." }],
      [3, "완벽하지 않아도 괜찮은 날이에요. 오늘은 할 일 하나쯤 내일로 미뤄도 세상은 멀쩡해요.", "It's fine not to be perfect today. Put one chore off until tomorrow, the world will be just fine.",
        { who: { en: "Monica", ko: "모니카" }, en: "Doesn't matter, I'll get 'em tomorrow. Or not. Whenever.", ko: "상관없어, 내일 치우지 뭐. 아님 말고. 아무 때나." }],
      [3, "생각보다 당신에게 가능성이 많아요. 스스로 선 긋지 말고 한번 도전해 보세요.", "You have more of a shot than you think. Don't rule yourself out, give it a try.",
        { who: { en: "Phoebe", ko: "피비" }, en: "You always see these really beautiful women with these really nothing guys, you could be one of those guys.", ko: "정말 예쁜 여자가 진짜 별 볼 일 없는 남자랑 있는 거 자주 보잖아, 너도 그런 남자가 될 수 있어." }],
      [2, "스스로를 너무 낮추기 쉬운 날이에요. 기죽는 마음이 들면 자신의 장점 하나를 떠올려 보세요.", "You may sell yourself short today. When you feel small, think of one thing you're good at.",
        { who: { en: "Chandler", ko: "챈들러" }, en: "Could she be more out of my league?", ko: "저 여자가 나한테 이보다 더 과분할 수 있을까?" }],
      [1, "기다리던 기회가 어긋날 수 있는 날이에요. 하지만 진짜 당신의 기회는 아직 오지 않았을지도 몰라요.", "A long-awaited chance may slip away today. But your real shot might still be on its way.",
        { who: { en: "Joey", ko: "조이" }, en: "I've done nothing but crappy plays for six years. And I finally get my shot, and I blow it!", ko: "6년 동안 형편없는 연극만 했는데, 드디어 온 기회를 날려버렸어!" }],
    ],
  },
  {
    code: "S01E07", title: "The One with the Blackout",
    moment: { ko: "도시 전체가 정전된 밤, 촛불 아래 모인 친구들", en: "A citywide blackout and friends by candlelight" },
    lucky: { ko: "촛불", en: "A candle" },
    fortunes: [
      [3, "익숙한 불빛이 꺼진 날엔 평소 못 보던 풍경이 보여요. 계획이 틀어져도 그 틈을 즐겨보세요.", "When the usual lights go out, you notice scenery you never saw. If plans fall through, enjoy the gap.",
        { who: { en: "Rachel", ko: "레이첼" }, en: "Wow, this is so cool, you guys. The entire city is blacked out!", ko: "와, 이거 완전 멋지다 얘들아. 도시 전체가 정전이야!" }],
      [4, "오늘은 먼저 건네는 미소 하나가 문을 열어줘요. 망설이지 말고 눈을 맞춰보세요.", "Today a single smile you offer first will open a door. Don't hesitate—make eye contact.",
        { who: { en: "Chandler", ko: "챈들러" }, en: "Do something. Just make contact, smile!", ko: "뭐라도 해. 눈 한번 맞추고, 웃어!" }],
      [5, "가슴 뛰는 일이 가까이 와 있어요. 설렘을 두려워하지 말고 그대로 따라가 보세요.", "Something heart-pounding is on its way. Don't fear the thrill—follow it.",
        { who: { en: "Ross", ko: "로스" }, en: "See, I see.... big passion in your future.", ko: "봐, 내 눈엔... 네 미래에 커다란 열정이 보여." }],
      [2, "오늘은 마음이 조금 식어 보일 수 있어요. 억지로 불붙이기보다 잔잔한 온기를 지키는 날이에요.", "Your heart may feel a bit cool today. Rather than forcing a spark, keep the quiet warmth going.",
        { who: { en: "Ross", ko: "로스" }, en: "But you know, I'll tell you something. Passion is way overrated.", ko: "근데 있잖아, 하나 말해줄게. 열정은 너무 과대평가됐어." }],
      [3, "미뤄둔 말이 있다면 오늘이 적당한 때예요. 기다림이 길어질수록 문은 좁아져요.", "If there's something you've been putting off saying, today is a fine time. The longer you wait, the narrower the door.",
        { who: { en: "Joey", ko: "조이" }, en: "If you don't ask her out soon you're going to end up stuck in the zone forever.", ko: "빨리 데이트 신청 안 하면 영원히 친구 존에 갇히게 될 거야." }],
      [2, "완벽한 타이밍만 기다리다 기회를 흘려보낼 수 있어요. 조금 어설퍼도 지금 움직여 보세요.", "Waiting for the perfect timing may let the chance slip away. Move now, even if it's a little clumsy.",
        { who: { en: "Ross", ko: "로스" }, en: "I will, I will. See, I'm waiting for the right moment.", ko: "할 거야, 할 거라고. 난 딱 맞는 순간을 기다리는 중이야." }],
      [1, "소식이 한 발 늦게 도착하는 날이에요. 서운해하기보다 먼저 물어보는 쪽이 마음 편해요.", "News reaches you a step late today. Asking first will sit better than feeling left out.",
        { who: { en: "Phoebe", ko: "피비" }, en: "This is so typical. I'm always the last one to know everything.", ko: "역시 이럴 줄 알았어. 난 맨날 뭐든 제일 늦게 알아." }],
      [5, "짧은 순간이 긴 시간보다 더 빛나는 하루예요. 오늘 스치는 설렘을 놓치지 마세요.", "A brief moment will shine brighter than long stretches today. Don't miss the flutter that passes by.",
        { who: { en: "Rachel", ko: "레이첼" }, en: "The first time he smiled at me... those three seconds were more exciting than three weeks in Bermuda with Barry.", ko: "그 사람이 처음 나한테 웃어줬을 때... 그 3초가 배리랑 간 버뮤다 3주보다 더 짜릿했어." }],
      [4, "곤란한 순간에 누군가 손을 내밀어 줄 거예요. 고맙다는 말은 아끼지 말고 크게 전하세요.", "Someone will lend you a hand in an awkward moment. Don't hold back your thanks—say it big.",
        { who: { en: "Chandler", ko: "챈들러" }, en: "Thanks for letting me use your phone... and for saving my life.", ko: "전화 쓰게 해줘서 고마워요... 그리고 내 목숨 구해준 것도요." }],
    ],
  },
  {
    code: "S01E08", title: "The One Where Nana Dies Twice",
    moment: { ko: "할머니와의 이별, 그리고 뜻밖의 반전", en: "Saying goodbye to Nana—with a twist" },
    lucky: { ko: "오래된 가족사진", en: "An old family photo" },
    fortunes: [
      [2, "조금 단조롭고 쓸쓸한 하루일 수 있어요. 소박한 한 끼라도 제대로 챙겨 드세요.", "Today may feel a little flat and lonely. Even if it's a simple meal, eat it properly.",
        { who: { en: "Chandler", ko: "챈들러" }, en: "Dehydrated Japanese noodles under fluorescent lights... does it get better than this?", ko: "형광등 아래서 먹는 건조 일본 라면... 이보다 좋을 수 있겠어?" }],
      [4, "당신의 장점을 알아봐 주는 사람이 곁에 있어요. 오늘은 칭찬을 그냥 기분 좋게 받아들이세요.", "Someone nearby sees your strengths. Today, just accept the compliments gladly.",
        { who: { en: "Phoebe", ko: "피비" }, en: "I dunno, 'cause you're smart, you're funny...", ko: "글쎄, 넌 똑똑하고, 웃기고..." }],
      [3, "남과 비교하면 괜히 멀리 가야 할 것 같아요. 당신만의 방식으로 마음을 전하는 게 더 빨라요.", "Comparing yourself makes it seem you must go far. Showing your heart your own way is quicker.",
        { who: { en: "Ross", ko: "로스" }, en: "I could do that. Just gotta go to Rome.", ko: "나도 할 수 있어. 로마에 가기만 하면 돼." }],
      [3, "오늘은 모든 걸 따지기보다 한 발 물러서는 게 평화로워요. 다만 꼭 필요한 말은 부드럽게 전하세요.", "Today, stepping back beats settling every score. Still, say what truly matters—gently.",
        { who: { en: "Mrs. Geller", ko: "겔러 부인" }, en: "I think some things are better left unsaid. I think it's nicer when people just get along.", ko: "어떤 건 말하지 않는 게 나아. 사람들끼리 그냥 잘 지내는 게 더 좋잖니." }],
      [5, "하늘도 당신 편인 날이에요. 창문을 열고 좋은 기운을 마음껏 들이세요.", "Even the sky is on your side today. Open the window and let the good energy in.",
        { who: { en: "Phoebe", ko: "피비" }, en: "God, what a great day. ...What? Weather-wise!", ko: "와, 정말 멋진 날이다. ...왜? 날씨 말이야!" }],
      [5, "곁에 있는 사람들이 가장 큰 행운이에요. 오늘은 사랑한다는 말을 아끼지 마세요.", "The people around you are your greatest luck. Don't hold back saying you love them today.",
        { who: { en: "Ross", ko: "로스" }, en: "I love you guys. You guys are the greatest.", ko: "너희 사랑해. 너희가 최고야." }],
      [1, "걱정하던 일이 고개를 들 수 있어요. 무리하지 말고 몸과 마음을 먼저 돌보세요.", "Something you feared may show its face. Don't push it—take care of your body and mind first.",
        { who: { en: "Ross", ko: "로스" }, en: "Just-just... having my worst fear realised...", ko: "그냥... 제일 무서워하던 일이 현실이 됐을 뿐이야..." }],
      [4, "일터에 뜻밖의 활기가 도는 날이에요. 동료와 가벼운 농담 한마디가 하루를 밝혀줘요.", "Unexpected energy fills your workplace today. A light joke with a coworker will brighten the day.",
        { who: { en: "Lowell", ko: "로웰" }, en: "It's like Mardi Gras without the paper mache heads.", ko: "종이탈만 없다 뿐이지 마르디 그라 축제 같아요." }],
    ],
  },
  {
    code: "S01E09", title: "The One Where Underdog Gets Away",
    moment: { ko: "문 밖에 갇혀버린 추수감사절", en: "A Thanksgiving locked out of the apartment" },
    lucky: { ko: "칠면조", en: "Turkey" },
    fortunes: [
      [5, "새로운 타이틀이 당신을 기다려요. 오늘은 스스로를 당당하게 소개해 보세요.", "A new title awaits you. Introduce yourself proudly today.",
        { who: { en: "Joey", ko: "조이" }, en: "As of today, I am officially Joey Tribbiani, actor slash model.", ko: "오늘부로 난 공식적으로 조이 트리비아니, 배우 겸 모델이야." }],
      [4, "계획이 어긋나도 새 자리를 만들 수 있어요. 오늘은 당신이 누군가의 따뜻한 식탁이 되어줄 거예요.", "Even if plans fall apart, you can set a new table. Today you'll be someone's warm place to gather.",
        { who: { en: "Monica", ko: "모니카" }, en: "How about I cook dinner at my place? I'll make it just like Mom's.", ko: "우리 집에서 내가 저녁 하면 어때? 엄마가 해주던 그대로 만들게." }],
      [1, "바라던 일이 손에서 미끄러질 수 있어요. 아쉬워도 괜찮아요, 다른 길이 곧 열려요.", "What you hoped for may slip away. It's okay to be disappointed—another path will open soon.",
        { who: { en: "Rachel", ko: "레이첼" }, en: "Forget Vail, forget seeing my family, forget shoop, shoop, shoop.", ko: "베일도 잊어, 가족 보는 것도 잊어, 슝슝슝도 잊어." }],
      [2, "오늘은 들뜬 분위기에 섞이기 어려울 수 있어요. 한 걸음만 다가가면 생각보다 따뜻할 거예요.", "You may find it hard to join the cheer today. Take just one step closer—it's warmer than you think.",
        { who: { en: "Chandler", ko: "챈들러" }, en: "I prefer to keep a safe distance from all this merriment.", ko: "난 이 모든 흥겨움에서 안전거리를 유지할래." }],
      [3, "놓친 기회 뒤에 뜻밖의 좋은 시간이 기다려요. 지금 곁에 있는 사람들과의 하루를 즐기세요.", "A missed chance leaves room for an unexpected good time. Enjoy the day with the people beside you.",
        { who: { en: "Rachel", ko: "레이첼" }, en: "The plane is gone, so it looks like I'm stuck here with you guys.", ko: "비행기는 떠났으니까, 너희랑 여기 갇혀 있게 됐네." }],
      [2, "오늘은 차선책으로 만족해야 할지 몰라요. 그래도 차선이 최악은 아니라는 걸 기억하세요.", "You may have to settle for plan B today. Remember, second best isn't the worst.",
        { who: { en: "Joey", ko: "조이" }, en: "We all had better plans. This was nobody's first choice.", ko: "우리 다 더 좋은 계획이 있었어. 이건 누구의 1순위도 아니었다고." }],
      [4, "누군가의 행복을 진심으로 기뻐하면 그 기운이 돌아와요. 오늘은 따뜻한 눈으로 주변을 바라보세요.", "Genuinely celebrating someone's happiness brings it back to you. Look around with warm eyes today.",
        { who: { en: "Phoebe", ko: "피비" }, en: "It's nice that he has someone.", ko: "그 사람한테도 누군가 있다니 다행이다." }],
      [5, "기다리던 소중한 만남이 다가오고 있어요. 설레는 마음을 노래처럼 표현해 보세요.", "A precious meeting you've awaited is drawing near. Let your excitement out like a song.",
        { who: { en: "Ross", ko: "로스" }, en: "Hey, hey, you're my baby, and I can't wait to meet you.", ko: "헤이, 헤이, 넌 내 아기야, 널 빨리 만나고 싶어." }],
    ],
  },
  {
    code: "S01E10", title: "The One with the Monkey",
    moment: { ko: "작은 원숭이 친구와 '혼자 오기' 새해 약속", en: "A little monkey and a 'no dates' New Year's pact" },
    lucky: { ko: "바나나", en: "A banana" },
    fortunes: [
      [1, "노력한 만큼 인정받지 못해 속상할 수 있어요. 오늘의 결과가 당신의 가치를 정하진 않아요.", "You may feel stung by not getting credit you earned. Today's result doesn't define your worth.",
        { who: { en: "Joey", ko: "조이" }, en: "It's just such a slap in the face, y'know?", ko: "완전 뺨 맞은 기분이야, 알아?" }],
      [4, "오늘은 오래된 친구들과의 약속이 가장 든든해요. 익숙한 얼굴들과 식탁을 나눠보세요.", "Plans with old friends are your best bet today. Share a table with familiar faces.",
        { who: { en: "Chandler", ko: "챈들러" }, en: "I say this year, no dates, we make a pact. Just the six of us- dinner.", ko: "올해는 데이트 없이 약속하자. 우리 여섯이서만 저녁 먹는 거야." }],
      [2, "같은 실수를 반복하면 신뢰가 닳아요. 오늘은 약속을 가볍게 여기지 마세요.", "Repeating the same mistake wears down trust. Don't take promises lightly today.",
        { who: { en: "Janice", ko: "재니스" }, en: "One of these times is just gonna be your last chance with me.", ko: "언젠가는 이번이 나한테 마지막 기회가 될 거야." }],
      [3, "혼자 끙끙대던 일에 간단한 해답이 있을지 몰라요. 가까운 사람의 조언에 귀 기울여 보세요.", "There may be a simple answer to what you've been wrestling with alone. Listen to advice from someone close.",
        { who: { en: "Monica", ko: "모니카" }, en: "Why don't you just get a roommate?", ko: "그냥 룸메이트를 구하지 그래?" }],
      [3, "아끼는 사람의 꿈을 응원하는 게 사랑일 때가 있어요. 놓아주는 용기가 서로를 키워요.", "Sometimes love means cheering on someone's dream. The courage to let go helps you both grow.",
        { who: { en: "Phoebe", ko: "피비" }, en: "You belong in Minsk. You can't stay here just 'cause of me.", ko: "넌 민스크에 가야 해. 나 때문에 여기 남으면 안 돼." }],
      [4, "짝이 없어도 괜찮아요. 여럿이 어울리는 자리에서 즐거움이 두 배가 돼요.", "It's fine not to have a partner. Fun doubles when everyone mingles together.",
        { who: { en: "Rachel", ko: "레이첼" }, en: "We'll have, we'll have a big party, and no-one'll know who's with who.", ko: "우리 큰 파티 하자, 그럼 누가 누구랑 왔는지 아무도 모를 거야." }],
      [5, "오늘은 맛있는 걸 마음껏 즐겨도 되는 날이에요. 작은 행복을 미루지 마세요.", "Today you can enjoy good food to your heart's content. Don't postpone small joys.",
        { who: { en: "Janice", ko: "재니스" }, en: "I love this artichoke thing! Oh, don't tell me what's in it, the diet starts tomorrow!", ko: "이 아티초크 요리 너무 좋아! 뭐 들었는지 말하지 마, 다이어트는 내일부터야!" }],
      [5, "노력의 결실이 반가운 소식으로 도착해요. 금전운과 기회가 함께 들어오는 날이에요.", "Your efforts bear fruit as welcome news. Money and opportunity arrive together today.",
        { who: { en: "Max", ko: "맥스" }, en: "We got the grant. Three years, all expenses paid.", ko: "지원금 받았어. 3년간, 경비 전액 지원이야." }],
      [1, "나만 소외된 것 같은 기분이 들 수 있어요. 그럴 땐 먼저 곁에 다가가 온기를 나눠보세요.", "You may feel like the only one left out. When you do, move closer and share some warmth first.",
        { who: { en: "Ross", ko: "로스" }, en: "Perfect. Perfect. So now everybody's getting kissed but me.", ko: "완벽하네. 완벽해. 이제 나만 빼고 다들 키스하는구나." }],
    ],
  },
  {
    code: "S01E11", title: "The One with Mrs. Bing",
    moment: { ko: "로맨스 소설가 엄마의 방문과 병원에서의 짝사랑", en: "A romance-novelist mom visits, and a crush in the hospital" },
    lucky: { ko: "로맨스 소설", en: "A romance novel" },
    fortunes: [
      [2, "한눈에 반할 만한 상대가 나타나도 서두르지 마세요. 마음을 주기 전에 조금 더 지켜보는 게 좋아요.", "Even if someone dazzling appears, don't rush. Watch a little longer before giving your heart.",
        { who: { en: "Monica", ko: "모니카" }, en: "Behind us is a guy who has the potential to break our hearts and plunge us into a pit of depression.", ko: "우리 뒤에 있는 남자, 우리 마음을 박살 내고 우울의 구렁텅이에 빠뜨릴 잠재력이 있어." }],
      [4, "지금 걱정하는 일은 생각보다 잘 풀려요. 스스로를 조금 더 믿어주세요.", "What you're worried about will turn out better than you think. Trust yourself a little more.",
        { who: { en: "Mrs. Bing", ko: "빙 부인" }, en: "You are gonna be fine, believe me.", ko: "넌 괜찮을 거야, 내 말 믿어." }],
      [4, "오늘은 평소 안 하던 걸 시도하기 좋은 날이에요. 작은 변화가 새로운 당신을 보여줄 거예요.", "A good day to try something you normally wouldn't. A small change will reveal a new you.",
        { who: { en: "Ross", ko: "로스" }, en: "But a man can change.", ko: "하지만 사람은 변할 수 있지." }],
      [3, "가까운 관계일수록 적당한 거리가 필요해요. 오늘은 혼자만의 시간도 챙겨보세요.", "The closer the bond, the more it needs some space. Make time for yourself today.",
        { who: { en: "Chandler", ko: "챈들러" }, en: "You guys spend waaaay too much time together.", ko: "너희 둘 같이 있는 시간이 너무너무 많아." }],
      [2, "알고 있는 비밀이 마음을 무겁게 할 수 있어요. 말할지 말지, 오늘은 신중하게 고르세요.", "A secret you know may weigh on you. Choose carefully today whether to speak.",
        { who: { en: "Joey", ko: "조이" }, en: "Y'know, knowledge is a tricky thing.", ko: "있잖아, 안다는 건 까다로운 거야." }],
      [5, "새로운 도전의 첫 장을 여는 날이에요. 서툴러도 시작한 것 자체가 큰 행운이에요.", "A day to open the first chapter of a new challenge. Clumsy or not, just starting is great luck.",
        { who: { en: "Rachel", ko: "레이첼" }, en: "Thought I'd give it a shot. I'm still on the first chapter.", ko: "한번 해볼까 싶었어. 아직 1장 쓰는 중이야." }],
      [1, "기대가 커서 실망도 클 수 있는 날이에요. 상상 속 모습보다 있는 그대로를 보세요.", "Big expectations may bring big disappointment today. See people as they are, not as you imagined.",
        { who: { en: "Phoebe", ko: "피비" }, en: "We thought you were different. But I guess it was just the coma.", ko: "네가 다른 줄 알았어. 근데 그냥 혼수상태라 그랬나 봐." }],
      [5, "당신의 재능이 크게 인정받는 날이에요. 자신 있게 당신의 이야기를 세상에 내놓으세요.", "Your talent earns big recognition today. Put your story out into the world with confidence.",
        { who: { en: "Mrs. Bing", ko: "빙 부인" }, en: "I have sold a hundred million copies of my books", ko: "난 내 책을 1억 부나 팔았어" }],
    ],
  },
  {
    code: "S01E12", title: "The One with the Dozen Lasagnas",
    moment: { ko: "라자냐 열두 판과 새 게임 테이블", en: "Twelve lasagnas and a new game table" },
    lucky: { ko: "푸스볼 테이블", en: "A foosball table" },
    fortunes: [
      [1, "컨디션이 흐트러지기 쉬운 하루예요. 중요한 결정은 잠시 미루고 쉬어가세요.", "An easily unsettled day. Put off big decisions and take a rest.",
        { who: { en: "Phoebe", ko: "피비" }, en: "I'm sorry, I'm just, I'm out of sorts.", ko: "미안, 그냥, 기분이 좀 이상해." }],
      [1, "해야 할 말이 무겁게 느껴질 수 있어요. 진심은 결국 전해지니 너무 겁내지 마세요.", "What you need to say may feel heavy. Sincerity gets through in the end, so don't be too afraid.",
        { who: { en: "Phoebe", ko: "피비" }, en: "She is gonna hate me.", ko: "걔가 날 미워할 거야." }],
      [2, "오늘은 약속 앞에서 망설임이 커질 수 있어요. 불안은 솔직히 나눌수록 작아져요.", "Hesitation may grow in the face of commitment today. Anxiety shrinks when you share it honestly.",
        { who: { en: "Chandler", ko: "챈들러" }, en: "It's a pretty big commitment, I mean, what if one of us wants to move out?", ko: "이거 꽤 큰 약속이잖아, 만약 우리 중 하나가 이사 나가고 싶어지면?" }],
      [2, "진실을 마주하는 게 조금 쓰라릴 수 있어요. 그래도 알고 나면 더 단단해질 거예요.", "Facing the truth may sting a little. But knowing will make you stronger.",
        { who: { en: "Rachel", ko: "레이첼" }, en: "I just liked it better before it was better...", ko: "그냥 더 나아지기 전이 더 좋았어..." }],
      [3, "오늘은 혼자만의 시간이 답을 줘요. 남의 기대 말고 내 마음에 귀를 기울여 보세요.", "Time alone gives you answers today. Listen to your own heart, not others' expectations.",
        { who: { en: "Rachel", ko: "레이첼" }, en: "I just need to be by myself for a while, you know? I just got to figure out what I want", ko: "한동안 혼자 있고 싶어, 알지? 내가 뭘 원하는지 알아내야 해" }],
      [3, "당신은 더 좋은 대접을 받을 자격이 있어요. 스스로의 가치를 낮추지 마세요.", "You deserve better treatment. Don't sell your own worth short.",
        { who: { en: "Ross", ko: "로스" }, en: "You deserve so much better than him", ko: "넌 그 사람보다 훨씬 더 좋은 사람을 만날 자격이 있어" }],
      [5, "기다리던 기쁜 소식이 도착해요. 오늘은 마음껏 소리 내어 기뻐하세요.", "Joyful news you've been waiting for arrives. Celebrate out loud today.",
        { who: { en: "Ross", ko: "로스" }, en: "I'm having a boy! Oh, I'm having a boy!", ko: "나 아들이야! 오, 나 아들 낳는대!" }],
      [4, "실용보다 즐거움을 택해도 괜찮은 날이에요. 친구와 함께 한바탕 놀면 기운이 솟아요.", "A day when choosing fun over practicality is fine. A good round of play with friends will recharge you.",
        { who: { en: "Joey", ko: "조이" }, en: "Who cares, we'll eat at the sink! Come on, let's play!", ko: "누가 신경 써, 싱크대에서 먹으면 되지! 자, 놀자!" }],
    ],
  },
  {
    code: "S01E13", title: "The One with the Boobies",
    moment: { ko: "노크 없이 문을 연 대가, 그리고 가족의 비밀", en: "The price of not knocking, and a family secret" },
    lucky: { ko: "수건", en: "A towel" },
    fortunes: [
      [5, "누군가의 그림자가 아니라 오늘은 온전히 나로 서는 날이에요. 내 방식대로 고른 길이 정답이 될 거예요.", "Today you stand as yourself, not in anyone's shadow. The path you choose your own way will turn out right.",
        { who: { en: "Chandler", ko: "챈들러" }, en: "You're not him. You're you.", ko: "넌 아버지가 아니야. 넌 너야." }],
      [5, "비교할 필요도 없이 당신이 빛나는 하루예요. 누군가 진심 어린 칭찬을 건네줄 거예요.", "You shine today, no comparison needed. Someone will offer you a heartfelt compliment.",
        { who: { en: "Joey", ko: "조이" }, en: "You're ten times prettier than she is.", ko: "엄마가 그 여자보다 열 배는 더 예뻐." }],
      [4, "남들이 몰라줘도 당신이 알아본 좋은 점은 진짜예요. 내 눈을 믿고 소중한 것을 지켜보세요.", "Even if others can't see it, the good you've spotted is real. Trust your own eyes and hold on to what's precious.",
        { who: { en: "Phoebe", ko: "피비" }, en: "But they don't see all the wonderfulness that I see.", ko: "근데 걔네는 내가 보는 멋진 점들을 못 봐." }],
      [3, "가까운 사람의 선택에 너무 끼어들지 마세요. 한 걸음 물러서 지켜보는 것도 큰 사랑이에요.", "Don't meddle too much in a loved one's choices. Stepping back and watching is a big kind of love too.",
        { who: { en: "Joey", ko: "조이" }, en: "Even if you know better, you've gotta let them make their own mistakes.", ko: "더 잘 안다고 해도, 그 사람들이 스스로 실수하게 놔둬야 해." }],
      [3, "익숙한 사람의 낯선 모습을 보게 될 수 있어요. 놀라기보다 한 사람으로 이해해보면 관계가 더 깊어져요.", "You may see an unfamiliar side of someone familiar. Try understanding them as a person rather than being shocked, and the bond will deepen.",
        { who: { en: "Rachel", ko: "레이첼" }, en: "Why can't parents just stay parents? Why do they have to become people?", ko: "왜 부모님은 그냥 부모님으로 있으면 안 되는 거야? 왜 사람이 되어야 하냐고?" }],
      [2, "허전한 마음을 간식으로 채우고 싶어지는 날이에요. 배보다 마음이 고픈 건 아닌지 먼저 살펴보세요.", "A day you may want to fill an empty feeling with snacks. Check first whether it's your heart that's hungry, not your stomach.",
        { who: { en: "Roger", ko: "로저" }, en: "Remember, they're just food, they're not love.", ko: "기억해, 그건 그냥 음식이지 사랑이 아니야." }],
      [2, "농담 뒤에 진심을 숨기기 쉬운 날이에요. 오늘은 한 번쯤 웃음기 없이 마음을 털어놓아 보세요.", "It's easy to hide your feelings behind jokes today. Try opening up once, without the punchline.",
        { who: { en: "Roger", ko: "로저" }, en: "You use your humour as a way of keeping people at a distance.", ko: "넌 유머를 사람들과 거리를 두는 수단으로 쓰잖아." }],
      [1, "어느 쪽을 택해도 곤란한 상황에 놓일 수 있어요. 대답을 서두르지 말고 잠시 숨을 고르세요.", "You may be caught where every answer is awkward. Don't rush to respond; take a breath first.",
        { who: { en: "Chandler", ko: "챈들러" }, en: "Rock, hard place, me.", ko: "진퇴양난, 바로 나." }],
      [1, "좋은 뜻으로 한 일이 엉키기 쉬운 날이에요. 이미 바뀐 것을 되돌리기보다 새 균형을 찾아보세요.", "Good intentions may get tangled today. Instead of turning back what's changed, look for a new balance.",
        { who: { en: "Mrs. Tribbiani", ko: "트리비아니 부인" }, en: "Now everything's screwed up. I just want it the way it was.", ko: "이제 다 엉망이 됐잖아. 난 그냥 예전 그대로이길 바랐어." }],
    ],
  },
  {
    code: "S01E14", title: "The One with the Candy Hearts",
    moment: { ko: "밸런타인데이의 소개팅과 추억 태우기 의식", en: "A Valentine's blind date and a boyfriend-bonfire ritual" },
    lucky: { ko: "하트 캔디", en: "A candy heart" },
    fortunes: [
      [5, "용기 내어 건넨 부탁에 기분 좋은 대답이 돌아와요. 망설이던 제안이 있다면 오늘 꺼내보세요.", "A brave request gets a happy answer. If there's an offer you've been holding back, make it today.",
        { who: { en: "Ross", ko: "로스" }, en: "She said yes.", ko: "그녀가 좋대." }],
      [5, "묵은 것을 정리하자마자 반가운 손님이 찾아오는 날이에요. 비운 자리에 좋은 인연이 들어올 거예요.", "Right after you clear out the old, welcome visitors arrive. Good connections will fill the space you've emptied.",
        { who: { en: "Phoebe", ko: "피비" }, en: "See, there you go, the cleansing works!", ko: "봐, 됐잖아, 정화 의식이 효과 있다니까!" }],
      [4, "엉뚱해 보이는 아이디어가 오히려 통하는 날이에요. 작고 소박한 핑계 하나로 대화를 시작해보세요.", "A quirky idea is exactly what works today. Start a conversation with one small, humble excuse.",
        { who: { en: "Chandler", ko: "챈들러" }, en: "Go with the egg, my friend.", ko: "그 달걀로 밀고 나가, 친구." }],
      [3, "오래 쉬었던 일에 다시 발을 들일 때가 됐어요. 완벽하지 않아도 일단 시작하면 감각이 돌아와요.", "It's time to step back into something you've paused. It doesn't need to be perfect; the feel comes back once you begin.",
        { who: { en: "Chandler", ko: "챈들러" }, en: "You gotta get back in the game here, ok?", ko: "너 다시 연애 시장에 뛰어들어야 돼, 알았지?" }],
      [3, "한 번의 실망으로 전부를 판단하지 마세요. 다음번은 분명 다를 거예요.", "Don't judge everything by one letdown. Next time will surely be different.",
        { who: { en: "Carol", ko: "캐롤" }, en: "Smile. They won't all be like this.", ko: "웃어. 다 이렇진 않을 거야." }],
      [2, "같은 실수가 반복된다면 패턴을 돌아볼 때예요. 나에게 맞지 않는 것을 알아보는 눈을 길러보세요.", "If the same mistake keeps repeating, it's time to look at the pattern. Train your eye for what isn't right for you.",
        { who: { en: "Rachel", ko: "레이첼" }, en: "How did we end up with these jerks? We're good people!", ko: "우린 어쩌다 이런 놈들만 만난 거야? 우린 좋은 사람들인데!" }],
      [2, "특별한 날이라는 이유로 아닌 걸 억지로 붙잡지 마세요. 혼자여도 괜찮은 하루예요.", "Don't cling to the wrong thing just because the day is special. It's fine to be on your own today.",
        { who: { en: "Monica", ko: "모니카" }, en: "You can go out with a creepy guy any night of the year.", ko: "이상한 남자랑은 1년 중 아무 날이나 만날 수 있잖아." }],
      [1, "피하고 싶은 말을 해야 하는 난처한 날이에요. 미룰수록 더 곤란해지니 솔직하게 정리하세요.", "An awkward day when you must say something you'd rather avoid. Putting it off only makes it worse, so be honest.",
        { who: { en: "Chandler", ko: "챈들러" }, en: "In my next life, I'm coming back as a toilet brush.", ko: "다음 생엔 변기 솔로 태어날 거야." }],
    ],
  },
  {
    code: "S01E15", title: "The One with the Stoned Guy",
    moment: { ko: "셰프 오디션 같은 저녁 식사와 승진 제안", en: "A make-or-break dinner audition and a promotion offer" },
    lucky: { ko: "요리 앞치마", en: "A cooking apron" },
    fortunes: [
      [5, "기다리던 기회가 문을 두드리는 날이에요. 설렘을 마음껏 누려도 좋아요.", "The chance you've waited for knocks today. Go ahead and enjoy the thrill.",
        { who: { en: "Monica", ko: "모니카" }, en: "I love my life, I love my life!", ko: "내 인생이 너무 좋아, 너무 좋아!" }],
      [4, "욕심도 부족함도 없는 딱 알맞은 선택을 하게 돼요. 적당함이 주는 편안함을 느껴보세요.", "You'll make a choice that is neither too much nor too little. Enjoy the comfort of just right.",
        { who: { en: "Monica", ko: "모니카" }, en: "Not too big, not too small. Just right.", ko: "너무 크지도, 너무 작지도 않아. 딱 좋아." }],
      [4, "잠시 멈칫했어도 실력은 어디 가지 않아요. 곁에서 믿어주는 사람의 말을 새겨들으세요.", "A stumble doesn't erase your skill. Take to heart the words of someone who believes in you.",
        { who: { en: "Ross", ko: "로스" }, en: "You'll get there. You're an amazing chef.", ko: "넌 결국 해낼 거야. 넌 대단한 요리사잖아." }],
      [3, "답을 모르겠다면 자리부터 바꿔보세요. 낯선 곳에서 뜻밖의 힌트를 얻을 수 있어요.", "If you don't know the answer, try changing where you stand. An unfamiliar place may give you an unexpected hint.",
        { who: { en: "Chandler", ko: "챈들러" }, en: "I don't know what I want to do. I just know I'm not going to figure it out working there.", ko: "내가 뭘 하고 싶은지 모르겠어. 거기서 일해선 그걸 알아낼 수 없다는 것만 알아." }],
      [3, "오래 기다린 만큼 조급해지기 쉬운 날이에요. 기회가 전부 진짜는 아니니 차분히 살펴보세요.", "Having waited so long, you may feel rushed. Not every opportunity is the real one, so look calmly.",
        { who: { en: "Monica", ko: "모니카" }, en: "I've waited seven years for an opportunity like this", ko: "이런 기회를 7년이나 기다렸다고" }],
      [2, "편한 선택이 나를 붙잡아둘까 고민되는 날이에요. 당장의 이득보다 원하는 방향을 먼저 떠올려보세요.", "You may worry an easy choice will hold you in place. Think of the direction you want before the quick gain.",
        { who: { en: "Chandler", ko: "챈들러" }, en: "If I took this promotion, it'd be like admitting that this is what I actually do.", ko: "이 승진을 받으면, 이게 진짜 내 일이라고 인정하는 거나 마찬가지야." }],
      [2, "남들의 꿈이 부러워 보여도 조급해하지 마세요. 꿈은 찾는 게 아니라 조금씩 모양을 갖춰가는 거예요.", "Even if others' dreams look enviable, don't panic. A dream isn't found all at once; it takes shape bit by bit.",
        { who: { en: "Chandler", ko: "챈들러" }, en: "You have goals. You have dreams. I don't have a dream.", ko: "너희는 목표가 있잖아. 꿈도 있고. 난 꿈이 없어." }],
      [1, "기대했던 일이 생각과 다르게 흘러갈 수 있어요. 실망은 잠깐, 더 맞는 기회를 위한 자리 비움이에요.", "Something you hoped for may go differently than planned. The disappointment is brief; it makes room for a better fit.",
        { who: { en: "Monica", ko: "모니카" }, en: "I thought this was, you know... it.", ko: "난 이게, 그러니까... 바로 그건 줄 알았어." }],
    ],
  },
  {
    code: "S01E16", title: "The One with Two Parts, Part 1",
    moment: { ko: "쌍둥이 자매의 등장과 출산 교실", en: "A twin sister appears, and a Lamaze class" },
    lucky: { ko: "손거울", en: "A hand mirror" },
    fortunes: [
      [5, "걱정했던 일이 생각보다 순조롭게 풀려요. 오늘은 마음을 조금 내려놓아도 좋아요.", "What you've worried about will go more smoothly than you think. You can loosen your grip a little today.",
        { who: { en: "Ross", ko: "로스" }, en: "Everything’s gonna be alright.", ko: "다 괜찮을 거야." }],
      [5, "새로운 역할 앞에서 떨려도 당신은 준비돼 있어요. 누군가의 응원이 큰 힘이 될 거예요.", "Even if a new role makes you nervous, you're ready. Someone's cheering will give you real strength.",
        { who: { en: "Rachel", ko: "레이첼" }, en: "You’re gonna be great!", ko: "넌 잘할 거야!" }],
      [4, "눈앞의 고비는 하루뿐이에요. 그 너머의 더 큰 그림을 보면 용기가 생겨요.", "The hurdle in front of you lasts just one day. Look at the bigger picture beyond it and courage will come.",
        { who: { en: "Susan", ko: "수잔" }, en: "The birth part is just one day, and when it’s over, we’re all gonna be parents for the rest of our lives.", ko: "출산은 딱 하루야. 그게 끝나면 우린 평생 부모가 되는 거고." }],
      [4, "머리로 알던 변화가 마음으로 와닿는 날이에요. 그 벅참이 당신을 한 뼘 더 자라게 할 거예요.", "A change you knew in your head finally reaches your heart. That full feeling will help you grow.",
        { who: { en: "Ross", ko: "로스" }, en: "I always knew I was havin’ a baby, I just never realised the baby was having me.", ko: "아기가 생긴다는 건 알았는데, 아기가 나를 갖게 된다는 건 몰랐어." }],
      [3, "어색하게 시작했다면 다시 시작하면 돼요. 가벼운 리셋이 흐름을 바꿔줄 거예요.", "If things started awkwardly, just start again. A light reset will change the flow.",
        { who: { en: "Chandler", ko: "챈들러" }, en: "Can we start over?", ko: "우리 처음부터 다시 할까요?" }],
      [3, "타이밍을 재는 것도 좋지만 너무 오래 기다리진 마세요. 완벽한 순간보다 솔직한 순간이 나아요.", "Timing matters, but don't wait too long. An honest moment beats a perfect one.",
        { who: { en: "Chandler", ko: "챈들러" }, en: "I’m just trying to find the right moment, you know?", ko: "그냥 적당한 타이밍을 찾고 있는 거야, 알지?" }],
      [2, "그리운 사람이 떠오르는 날이에요. 그 마음을 곁에 있는 사람들에게 조금 나눠보세요.", "Someone you miss comes to mind today. Share a little of that feeling with the people beside you.",
        { who: { en: "Phoebe", ko: "피비" }, en: "What I really want is for my mom to be alive and enjoy it with me.", ko: "내가 진짜 원하는 건 엄마가 살아 계셔서 나랑 같이 즐기는 거야." }],
      [2, "일과 사적인 감정을 섞기 쉬운 날이에요. 선을 지키면 둘 다 지킬 수 있어요.", "Work and personal feelings may blur today. Keep the line and you'll protect both.",
        { who: { en: "Ross", ko: "로스" }, en: "You don’t dip your pen in the company ink.", ko: "회사 잉크에 펜을 담그는 거 아니야." }],
      [1, "벅차 보이는 일 앞에서 주저앉고 싶어질 수 있어요. 한 번에 다 하려 말고 숨 한 번부터 쉬세요.", "You may want to give up before something that seems overwhelming. Don't do it all at once; start with one breath.",
        { who: { en: "Carol", ko: "캐롤" }, en: "This is impossible. It’s just impossible.", ko: "이건 불가능해. 그냥 불가능하다고." }],
    ],
  },
  {
    code: "S01E17", title: "The One with Two Parts, Part 2",
    moment: { ko: "발목 부상과 보험 카드 바꿔치기 소동", en: "A sprained ankle and an insurance-card swap" },
    lucky: { ko: "보험 카드", en: "An insurance card" },
    fortunes: [
      [5, "당신의 성실함을 알아주는 사람이 나타나요. 스스로를 조금 더 믿어도 좋은 날이에요.", "Someone will recognize how dependable you are. It's a good day to trust yourself a bit more.",
        { who: { en: "Chandler", ko: "챈들러" }, en: "You're one of the most caring, most responsible men in North America.", ko: "넌 북미에서 제일 다정하고 제일 책임감 있는 남자야." }],
      [5, "위기의 순간에 당신이 든든한 버팀목이 돼요. 해낸 일을 스스로 인정해주세요.", "In a tough moment, you become someone's steady support. Give yourself credit for what you pulled off.",
        { who: { en: "Chandler", ko: "챈들러" }, en: "You came through, you did what you had to do. That is very dad.", ko: "넌 해냈어, 해야 할 일을 했잖아. 그게 바로 아빠야." }],
      [4, "지난 아쉬움을 채울 기회가 찾아와요. 가족이나 오랜 인연과 함께할 계획을 세워보세요.", "A chance to make up for past regrets arrives. Plan something with family or an old friend.",
        { who: { en: "Mr. Geller", ko: "겔러 씨" }, en: "There's time to make up for that. We can do stuff together.", ko: "그걸 만회할 시간은 있어. 우리 같이 뭐든 할 수 있잖아." }],
      [4, "오늘 당신의 모습이 누군가의 마음에 오래 남아요. 있는 그대로 당당히 나서보세요.", "The way you look today will stay in someone's heart. Step out confidently as you are.",
        { who: { en: "Joey", ko: "조이" }, en: "You have never looked so beautiful.", ko: "너 지금처럼 아름다웠던 적이 없어." }],
      [3, "아쉬운 작별이 있어도 좋은 기억은 남아요. 마음을 정리하는 데 시간을 넉넉히 주세요.", "Even a bittersweet goodbye leaves good memories. Give yourself plenty of time to let go.",
        { who: { en: "Phoebe", ko: "피비" }, en: "You're gonna be really, really hard to get over.", ko: "너 정말, 정말 잊기 힘들 거야." }],
      [3, "오랜만의 만남에서 반가운 익숙함을 느껴요. 변하지 않는 것에서 위안을 찾아보세요.", "A long-awaited reunion feels comfortingly familiar. Find reassurance in what hasn't changed.",
        { who: { en: "Ursula", ko: "어슐라" }, en: "You have not changed!", ko: "너 하나도 안 변했구나!" }],
      [2, "약속이 어긋나 서운할 수 있어요. 섭섭함은 솔직하게, 하지만 부드럽게 전해보세요.", "A broken promise may leave you hurt. Say how you feel honestly, but gently.",
        { who: { en: "Phoebe", ko: "피비" }, en: "Don't you hate it when people aren't there for you?", ko: "필요할 때 사람들이 곁에 없으면 정말 싫지 않아?" }],
      [1, "예상치 못한 지출이 생길 수 있어요. 오늘은 무리한 계획을 피하고 안전을 먼저 챙기세요.", "An unexpected expense may pop up. Avoid risky plans today and put safety first.",
        { who: { en: "Monica", ko: "모니카" }, en: "X-rays alone could be a couple hundred dollars.", ko: "엑스레이만 해도 몇백 달러는 나올 거야." }],
    ],
  },
  {
    code: "S01E18", title: "The One with All the Poker",
    moment: { ko: "남자팀 대 여자팀 포커 대결과 꿈의 직장 면접", en: "Guys vs. girls poker and a dream-job interview" },
    lucky: { ko: "포커 칩", en: "A poker chip" },
    fortunes: [
      [5, "좋아하는 일이 기회로 연결되는 날이에요. 당신의 취향이 곧 경쟁력이에요.", "Something you love turns into an opportunity today. Your taste is your strength.",
        { who: { en: "Rachel", ko: "레이첼" }, en: "I would be shopping... for a living!", ko: "쇼핑하는 게... 직업이 되는 거야!" }],
      [5, "나에게 꼭 맞는 자리가 손짓해요. 끌리는 곳이 있다면 망설이지 말고 향해보세요.", "A place that truly fits you is calling. If something pulls at you, head toward it without hesitation.",
        { who: { en: "Phoebe", ko: "피비" }, en: "It's like the mother ship is calling you home.", ko: "모선이 너를 집으로 부르는 것 같네." }],
      [4, "서툴러도 직접 부딪혀보면 금세 익숙해져요. 오늘은 도전하는 쪽에 행운이 있어요.", "Even if you're new at it, diving in helps you learn fast. Luck favors the one who tries today.",
        { who: { en: "Rachel", ko: "레이첼" }, en: "I think I'm gonna give it a go.", ko: "한번 해볼까 봐." }],
      [4, "작은 너그러움이 큰 호감으로 돌아와요. 처음인 사람에게 따뜻하게 손 내밀어 보세요.", "A little generosity comes back as goodwill. Reach out warmly to someone who's new.",
        { who: { en: "Joey", ko: "조이" }, en: "It's their first time, why don't we just forget about the money, alright?", ko: "처음이잖아, 돈 얘기는 그냥 잊자, 응?" }],
      [3, "하나를 놓쳐도 끝이 아니에요. 문은 생각보다 많이 열려 있어요.", "Missing one chance isn't the end. More doors are open than you think.",
        { who: { en: "Phoebe", ko: "피비" }, en: "There's gonna be lots of other stuff.", ko: "다른 기회는 얼마든지 있을 거야." }],
      [2, "오늘은 운이 따라주지 않아도 너무 애쓰지 마세요. 판을 쉬어가는 것도 전략이에요.", "If luck isn't with you today, don't force it. Sitting out a hand is also strategy.",
        { who: { en: "Ross", ko: "로스" }, en: "When you don't have the cards, you don't have the cards", ko: "패가 안 들어오면, 안 들어오는 거야" }],
      [1, "충동적인 소비는 오늘 꼭 피하세요. 지갑을 닫아두는 게 행운을 지키는 길이에요.", "Steer clear of impulse spending today. Keeping your wallet closed is how you protect your luck.",
        { who: { en: "Phoebe", ko: "피비" }, en: "So now bad things will happen to he who spends it.", ko: "이제 이 돈을 쓰는 사람한테 나쁜 일이 생길 거야." }],
      [1, "속상한 마음에 판을 키우고 싶어지는 날이에요. 감정이 가라앉을 때까지 큰 결정은 미뤄두세요.", "Frustration may tempt you to raise the stakes. Hold off on big decisions until your feelings settle.",
        { who: { en: "Rachel", ko: "레이첼" }, en: "I just lost a job, and I'd like to raise the bet five bucks.", ko: "방금 일자리를 놓쳤으니까, 판돈을 5달러 올릴래." }],
    ],
  },
  {
    code: "S01E19", title: "The One Where the Monkey Gets Away",
    moment: { ko: "맡아둔 원숭이가 사라진 대소동", en: "The great escape of a borrowed monkey" },
    lucky: { ko: "동물 간식", en: "A pet treat" },
    fortunes: [
      [4, "편안함과 설렘은 함께 올 수 있어요. 가까이 있는 사람을 새로운 눈으로 한번 바라보세요.", "Comfort and sparks can come together. Take a fresh look at someone who's already close.",
        { who: { en: "Rachel", ko: "레이첼" }, en: "Do you think you can ever have both? Y'know? Someone who's like, who's like your best friend, but then also can make your toes curl?", ko: "둘 다 가질 수 있을까? 베프 같은데 발끝까지 짜릿하게 해주는 사람 말이야." }],
      [5, "오늘은 작은 부적 하나가 큰 힘을 줘요. 아끼는 물건을 챙겨 나가면 행운이 따라올 거예요.", "A small charm carries big power today. Bring something you treasure and luck will tag along.",
        { who: { en: "Phoebe", ko: "피비" }, en: "'Cause the left one is lucky...", ko: "왼쪽 거는 행운의 신발이거든..." }],
      [3, "생각보다 말이 먼저 나가기 쉬운 날이에요. 한 박자만 쉬어가면 충분해요.", "Words may outrun your thoughts today. One beat of pause is all you need.",
        { who: { en: "Phoebe", ko: "피비" }, en: "Yes, but there isn't always time!", ko: "응, 근데 항상 그럴 시간이 있는 건 아니잖아!" }],
      [1, "잃어버린 것에 마음이 쏠리는 날이에요. 하지만 찾는 발걸음은 헛되지 않으니, 조금만 더 둘러보세요.", "Your heart may fixate on what's lost today. Keep looking a little longer; the search isn't in vain.",
        { who: { en: "Ross", ko: "로스" }, en: "He's gone, he's-he's just gone.", ko: "없어졌어, 그냥 사라졌다고." }],
      [2, "의도와 다르게 일이 꼬일 수 있어요. 변명보다 진심 어린 사과 한마디가 관계를 지켜줄 거예요.", "Things may go wrong despite good intentions. A sincere apology will guard the bond better than excuses.",
        { who: { en: "Rachel", ko: "레이첼" }, en: "Y'know, it is not like I did this on purpose.", ko: "있잖아, 내가 일부러 그런 것도 아니잖아." }],
      [3, "지나간 일이 멀게 느껴진다면 그만큼 성장했다는 뜻이에요. 오늘은 옛 사진을 보며 웃어보세요.", "If the past feels distant, it means you've grown. Look at old photos and smile today.",
        { who: { en: "Monica", ko: "모니카" }, en: "Gosh, doesn't it seem like a million years ago?", ko: "세상에, 백만 년 전 일 같지 않아?" }],
      [1, "오늘은 기대했던 도움이 오지 않을 수 있어요. 스스로 해낼 방법을 미리 준비해두세요.", "The help you counted on may not come today. Have your own plan ready.",
        { who: { en: "Luisa", ko: "루이자" }, en: "I could... but I won't.", ko: "도와줄 수는 있지... 근데 안 할 거야." }],
      [5, "자유로운 하루가 펼쳐져요. 가고 싶었던 곳으로 마음 가는 대로 떠나보세요.", "A free day unfolds before you. Follow your heart to the place you've been longing to go.",
        { who: { en: "Joey", ko: "조이" }, en: "You're a monkey. You're loose in the city. Where do you go?", ko: "네가 원숭이야. 도시에 풀려났어. 어디로 갈래?" }],
      [4, "꼬인 관계도 부드러운 말 한마디로 풀릴 수 있어요. 먼저 웃으며 손 내밀어 보세요.", "A tangled situation can loosen with one kind word. Reach out first, with a smile.",
        { who: { en: "Monica", ko: "모니카" }, en: "I'm sure there's some friendly way to reconcile this!", ko: "분명 좋게 해결할 방법이 있을 거야!" }],
    ],
  },
  {
    code: "S01E20", title: "The One with the Evil Orthodontist",
    moment: { ko: "끝난 연애로의 유혹과 오지 않는 전화", en: "Temptation to go back, and a call that never comes" },
    lucky: { ko: "전화기", en: "A telephone" },
    fortunes: [
      [3, "익숙한 것이 주는 위로를 누려도 괜찮아요. 다만 편안함과 정답은 다를 수 있다는 걸 기억하세요.", "It's fine to enjoy the comfort of the familiar. Just remember comfortable isn't always right.",
        { who: { en: "Rachel", ko: "레이첼" }, en: "It was comfortable, it was familiar... it was just nice!", ko: "편하고, 익숙하고... 그냥 좋았어!" }],
      [1, "연락을 기다리며 속이 타는 날이에요. 휴대폰을 잠시 내려놓으면 마음이 한결 가벼워질 거예요.", "A day of anxiously waiting for a reply. Put the phone down for a while and your heart will feel lighter.",
        { who: { en: "Chandler", ko: "챈들러" }, en: "Now I'm needy and snubbed. God, I miss just being needy.", ko: "이제 난 매달리는 데다 무시까지 당했어. 그냥 매달리기만 하던 때가 그립다." }],
      [2, "자존심이 발목을 잡을 수 있어요. 오늘만큼은 먼저 다가가는 쪽이 이기는 거예요.", "Pride may hold you back today. This time, the one who reaches out first wins.",
        { who: { en: "Chandler", ko: "챈들러" }, en: "I can't call her, I left a message! I have some pride.", ko: "전화 못 해, 메시지 남겼잖아! 나도 자존심이 있어." }],
      [5, "오래 품어온 의문에 답이 오는 날이에요. 당신의 선택이 옳았다는 확신이 생길 거예요.", "A long-held question finds its answer today. You'll feel sure your choice was right.",
        { who: { en: "Rachel", ko: "레이첼" }, en: "Ever since I ran out on Barry at the wedding, I have wondered whether I made the right choice. And now I know.", ko: "결혼식에서 배리를 버리고 도망친 뒤로 늘 옳은 선택이었나 궁금했거든. 이제 알겠어." }],
      [5, "누군가 당신을 멀리서 동경하고 있어요. 오늘은 뜻밖의 칭찬이 하루를 환하게 밝혀줄 거예요.", "Someone admires you from afar. An unexpected compliment will light up your day.",
        { who: { en: "Joey", ko: "조이" }, en: "She said you looked like Ingrid Bergman that day.", ko: "그날 네가 잉그리드 버그만 같았대." }],
      [4, "망설이던 연락, 오늘 하세요. 생각보다 반가운 목소리가 돌아올 거예요.", "Make that call you've been putting off. A warmer voice than you expect will answer.",
        { who: { en: "Phoebe", ko: "피비" }, en: "Just do it! Call her!", ko: "그냥 해! 전화하라고!" }],
      [1, "조금 험한 하루가 될 수 있어요. 몸을 사리고 익숙한 곳에 머무는 게 좋아요.", "It may be a rough day out there. Lie low and stay somewhere familiar.",
        { who: { en: "Phoebe", ko: "피비" }, en: "Not a good day for birds...", ko: "새들한테는 운 없는 날이네..." }],
      [4, "꾸준히 해온 일에 드디어 변화가 보여요. 지금 방향 그대로 조금만 더 가보세요.", "Your steady effort is finally showing results. Keep going in the same direction a little longer.",
        { who: { en: "Barry", ko: "배리" }, en: "I think we're starting to see some real progress here.", ko: "진짜로 진전이 보이기 시작하는 것 같네요." }],
    ],
  },
  {
    code: "S01E21", title: "The One with the Fake Monica",
    moment: { ko: "내 이름으로 사는 낯선 사람과 탭댄스 수업", en: "A stranger living under your name, and tap class" },
    lucky: { ko: "탭댄스 슈즈", en: "Tap shoes" },
    fortunes: [
      [5, "오늘 만나는 사람이 당신에게 새로운 활력을 불어넣어줄 거예요. 그 에너지를 마음껏 받아들이세요.", "Someone you meet today will breathe new energy into you. Soak it up.",
        { who: { en: "Monica", ko: "모니카" }, en: "She is this astounding person, with this, with this amazing spirit.", ko: "그 여자는 정말 놀라운 사람이야, 엄청난 에너지를 가졌어." }],
      [4, "구경꾼으로 남기엔 아까운 날이에요. 직접 뛰어들 때 진짜 즐거움이 찾아와요.", "Too good a day to just watch. The real fun comes when you jump in.",
        { who: { en: "Teacher", ko: "댄스 선생님" }, en: "You don't observe a dance class. You dance a dance class.", ko: "댄스 수업은 구경하는 게 아니에요. 추는 거지." }],
      [5, "서툴러도 괜찮아요. 시작한 당신은 이미 누구보다 앞서 있어요.", "Clumsy is fine. By starting, you're already ahead of the rest.",
        { who: { en: "Monica", ko: "모니카" }, en: "At least I'm doing it!", ko: "적어도 난 하고 있잖아!" }],
      [2, "일이 손에 잘 안 붙는 날이에요. 완벽하려 하기보다 한 동작씩 천천히 익혀보세요.", "Things may not click today. Rather than aim for perfect, learn one step at a time.",
        { who: { en: "Monica", ko: "모니카" }, en: "Did you ever feel like sometimes you are just so unbelievably uncoordinated?", ko: "가끔 내가 믿을 수 없을 만큼 몸치라고 느낀 적 없어?" }],
      [3, "잠깐의 일탈도 좋지만 결국 제자리가 당신을 기다려요. 변하지 않는 나다움도 소중하다는 걸 느끼게 될 거예요.", "A little adventure is nice, but your own place awaits. You'll find value in staying true to yourself.",
        { who: { en: "Fake Monica", ko: "가짜 모니카" }, en: "You're gonna go back to being exactly who you were, because that's who you are.", ko: "넌 원래 모습으로 돌아갈 거야, 그게 너니까." }],
      [1, "지갑을 조심해야 할 날이에요. 충동구매는 하루만 미루고 카드 내역을 한번 확인해보세요.", "Guard your wallet today. Delay impulse buys and check your card statements.",
        { who: { en: "Monica", ko: "모니카" }, en: "It's just such reckless spending.", ko: "정말 너무 무모한 지출이야." }],
      [2, "남의 삶이 유난히 부러워 보일 수 있어요. 비교는 잠시 접고 내가 가진 것을 세어보세요.", "Others' lives may look extra enviable today. Set comparison aside and count what you have.",
        { who: { en: "Monica", ko: "모니카" }, en: "She's got everything I want, and she doesn't have my mother.", ko: "그 여자는 내가 원하는 걸 다 가졌어, 우리 엄마만 빼고." }],
      [4, "꾸밈없는 말이 가장 큰 울림을 줘요. 오늘은 마음을 솔직하게 전해보세요.", "Plain words resonate the most. Say what's in your heart today.",
        { who: { en: "Ross", ko: "로스" }, en: "Just, just say what you feel.", ko: "그냥 느끼는 대로 말해." }],
    ],
  },
  {
    code: "S01E22", title: "The One with the Ick Factor",
    moment: { ko: "나이를 속인 연인과 늘 울리지 않는 삐삐", en: "A date who fibbed about age, and a pager on standby" },
    lucky: { ko: "삐삐", en: "A pager" },
    fortunes: [
      [3, "계획대로 되지 않아도 괜찮아요. 흘러가는 대로 두면 뜻밖의 순간이 찾아올 거예요.", "It's okay if things don't go to plan. Let them flow and an unexpected moment will come.",
        { who: { en: "Monica", ko: "모니카" }, en: "Things happen, and they happen. You don't plan these things.", ko: "일어날 일은 일어나는 거야. 이런 건 계획하는 게 아니잖아." }],
      [4, "나이는 숫자일 뿐이에요. 늦었다고 생각한 일에 오늘 도전해보세요.", "Age is just a number. Try something today you thought you were too late for.",
        { who: { en: "Monica", ko: "모니카" }, en: "What the hell does it matter how old we are.", ko: "나이가 몇 살이든 그게 무슨 상관이야." }],
      [2, "자리가 바뀌면 사람들의 시선도 달라져요. 서운해하기보다 새로운 거리감을 받아들여 보세요.", "A new position changes how others see you. Accept the new distance instead of feeling hurt.",
        { who: { en: "Chandler", ko: "챈들러" }, en: "Just because I'm in charge doesn't mean I'm a different person.", ko: "내가 책임자가 됐다고 다른 사람이 된 건 아니야." }],
      [4, "당신의 진짜 모습을 보여줄 기회가 와요. 편하게 어울리면 좋은 인상이 남을 거예요.", "A chance to show your true self is coming. Just relax and mingle; you'll leave a great impression.",
        { who: { en: "Phoebe", ko: "피비" }, en: "Let them see what a great guy you still are.", ko: "네가 여전히 얼마나 좋은 사람인지 보여줘." }],
      [1, "관계에 선이 생기는 날일 수 있어요. 모두와 가까울 수는 없다는 걸 받아들이면 마음이 편해져요.", "Lines may be drawn in your relationships today. Accepting you can't be close to everyone brings peace.",
        { who: { en: "Phoebe", ko: "피비" }, en: "But they're not your friends anymore.", ko: "근데 그 사람들은 이제 네 친구가 아니야." }],
      [1, "애써도 안 풀리는 일이 있어요. 오늘은 억지로 붙잡기보다 한 발 물러서는 용기가 필요해요.", "Some things won't work out however hard you try. Today calls for the courage to step back.",
        { who: { en: "Monica", ko: "모니카" }, en: "Sometimes just things doesn't work out.", ko: "가끔은 그냥 안 되는 일도 있어." }],
      [3, "생소한 일에도 의외의 재능이 숨어 있어요. 작은 임시 역할이 새로운 경험이 될 거예요.", "Hidden talents may lie in unfamiliar work. A small temporary role could be a fresh experience.",
        { who: { en: "Phoebe", ko: "피비" }, en: "I could be a secretary.", ko: "나도 비서 할 수 있어." }],
      [5, "새로운 곳에서 좋은 사람들을 만나요. 첫날의 설렘이 오래도록 이어질 거예요.", "You'll meet kind people in a new place. First-day excitement will last a long while.",
        { who: { en: "Phoebe", ko: "피비" }, en: "Oh, exellent. Everyone was so, so nice.", ko: "완전 최고였어. 다들 너무너무 친절했어." }],
      [5, "가족이나 가까운 사람에게 기쁜 소식이 찾아와요. 새로운 역할이 당신을 더 따뜻하게 만들어줄 거예요.", "Joyful news arrives for family or someone close. A new role will make you even warmer.",
        { who: { en: "Monica", ko: "모니카" }, en: "I can't belive it, I'm gonna be an aunt.", ko: "믿기지 않아, 나 이모가 된다고." }],
    ],
  },
  {
    code: "S01E23", title: "The One with the Birth",
    moment: { ko: "기다리던 아기가 태어난 날", en: "The day the baby finally arrived" },
    lucky: { ko: "아기 양말", en: "Baby socks" },
    fortunes: [
      [4, "기다림이 길어질 수 있지만 즐길 거리를 챙기면 괜찮아요. 오늘은 좋아하는 노래 한 곡이 행운의 열쇠예요.", "The wait may be long, but bring something to enjoy. A favorite song is today's lucky key.",
        { who: { en: "Phoebe", ko: "피비" }, en: "I just thought we might be here for awhile. You know, things might get musical.", ko: "한참 있어야 할 것 같아서. 음악이 필요할지도 모르잖아." }],
      [3, "같은 말도 언제 하느냐가 중요해요. 오늘은 분위기를 살피고 말할 때를 골라보세요.", "When you say it matters as much as what. Read the room and choose your moment today.",
        { who: { en: "Chandler", ko: "챈들러" }, en: "You have to pick your moments.", ko: "타이밍을 잘 골라야지." }],
      [5, "혼자라고 느낄 틈이 없을 거예요. 든든한 사람들이 당신 곁을 지켜줄 거예요.", "You won't have a moment to feel alone. Steady people will stand by your side.",
        { who: { en: "Rachel", ko: "레이첼" }, en: "We are going to find them, and until we do, we are all here for you, ok?", ko: "우리가 꼭 찾아낼 거고, 그때까지 우리 모두 네 곁에 있을게, 알았지?" }],
      [2, "모든 준비가 끝나길 기다려주지 않는 일이 있어요. 부족한 대로 지금 시작해야 할 때예요.", "Some things won't wait until everything's ready. It's time to start as you are.",
        { who: { en: "Dr. Franzblau", ko: "프란츠블라우 박사" }, en: "I can't tell the baby to wait for them.", ko: "아기한테 그 사람들 올 때까지 기다리라고 할 순 없어요." }],
      [2, "당장 성과가 없어도 실망하지 마세요. 지금은 기초를 다지는 시기예요.", "Don't be discouraged by slow results. This is a season for laying foundations.",
        { who: { en: "Lydia", ko: "리디아" }, en: "It's a rebuilding year.", ko: "올해는 재정비하는 해야." }],
      [5, "기다려온 결실을 드디어 마주하게 돼요. 벅찬 감동을 마음껏 누리세요.", "You'll finally meet the fruit of your long wait. Savor the overwhelming joy.",
        { who: { en: "Phoebe", ko: "피비" }, en: "You guys, he's beautiful!", ko: "얘들아, 너무 예쁘다!" }],
      [4, "작은 배려가 큰 사랑이 돼요. 주머니 속 사탕 하나라도 누군가와 나눠보세요.", "Small kindnesses add up to big love. Share even a single candy from your pocket.",
        { who: { en: "Monica", ko: "모니카" }, en: "I will always have gum.", ko: "나한텐 언제나 껌이 있을 거야." }],
      [1, "다툼이 길어지면 둘 다 문밖으로 밀려날 수 있어요. 오늘은 경쟁보다 협력을 택하세요.", "Keep squabbling and you may both be shown the door. Choose cooperation over rivalry today.",
        { who: { en: "Carol", ko: "캐롤" }, en: "All right, that's it. I want both of you out.", ko: "좋아, 됐어. 둘 다 나가." }],
    ],
  },
  {
    code: "S01E24", title: "The One Where Rachel Finds Out",
    moment: { ko: "생일날 알게 된 비밀, 그리고 공항의 엇갈림", en: "A birthday secret revealed, and a near-miss at the airport" },
    lucky: { ko: "비행기 표", en: "A plane ticket" },
    fortunes: [
      [5, "친구의 진심 어린 한마디가 마음을 채워줘요. 오늘은 당신도 고마운 사람에게 마음을 표현해보세요.", "A friend's heartfelt words will fill you up. Tell someone you're grateful for how you feel.",
        { who: { en: "Joey", ko: "조이" }, en: "We want you to be happy. And I may only have a couple beers in me, but... I love you, man.", ko: "우린 네가 행복하길 바라. 맥주 몇 잔 마셔서 그런지 몰라도... 사랑한다, 친구야." }],
      [4, "큰 변화의 문이 열리고 있어요. 두려워 말고 새로운 페이지를 넘겨보세요.", "A door to big change is opening. Don't fear it; turn the new page.",
        { who: { en: "Phoebe", ko: "피비" }, en: "I don't think any of our lives are ever gonna be the same ever again.", ko: "우리 인생은 이제 절대 예전 같지 않을 거야." }],
      [3, "답이 안 나올 땐 직접 마주해보세요. 머리보다 마음이 먼저 알려줄 거예요.", "When no answer comes, face it in person. Your heart will know before your head.",
        { who: { en: "Rachel", ko: "레이첼" }, en: "Maybe I'll know when I see him.", ko: "얼굴 보면 알게 되겠지." }],
      [1, "걱정이 앞서 시작도 전에 멈칫하게 되는 날이에요. 결과를 미리 단정하지 마세요.", "Worry may stop you before you begin today. Don't decide the ending in advance.",
        { who: { en: "Rachel", ko: "레이첼" }, en: "Sometimes it doesn't.", ko: "가끔은 안 될 때도 있잖아." }],
      [1, "마음이 복잡해 결정을 내리기 힘든 날이에요. 서두르지 말고 조금 더 시간을 두세요.", "A tangled heart makes decisions hard today. Don't rush; give it more time.",
        { who: { en: "Rachel", ko: "레이첼" }, en: "Ross, it's too hard.", ko: "로스, 너무 어려워." }],
      [3, "미련을 내려놓고 눈앞의 여정에 집중할 때예요. 새로운 맛과 경험이 기분을 바꿔줄 거예요.", "Let go of lingering feelings and focus on the journey ahead. New tastes and experiences will lift your mood.",
        { who: { en: "Joey", ko: "조이" }, en: "Move on. Go to China. Eat Chinese food.", ko: "잊어. 중국 가. 중국 음식 먹어." }],
      [2, "불편한 말은 급하게 꺼내지 않아도 돼요. 오늘은 타이밍을 조금 미루는 게 지혜예요.", "Hard news needn't be rushed. Today, waiting a little is the wise move.",
        { who: { en: "Joey", ko: "조이" }, en: "If you're just gonna, like, break his heart, that's the kind of thing that can wait.", ko: "마음 아프게 할 얘기라면, 그건 좀 기다려도 돼." }],
      [5, "새로운 자리에서 환영받게 돼요. 긴장 풀고 당신답게 다가가세요.", "You'll be welcomed somewhere new. Relax and simply be yourself.",
        { who: { en: "Ross", ko: "로스" }, en: "They're gonna love you.", ko: "다들 널 좋아할 거야." }],
    ],
  },
];
