// 프렌즈 시즌1 GIPHY GIF 목록 (출처: https://giphy.com/friends/seasons/season-1)
// 에피소드 코드별 [GIF id, [나오는 주인공]] — 영상 주소: https://media.giphy.com/media/{id}/giphy.mp4

window.GIFS = {
  S01E01: [
    ["U8YJW2KYT76MKNvDKG", []],
    ["SwmYRaqcowXczDPAxP", ["Monica"]],
    ["LoUmCyntgoQA6Rf2Mz", ["Rachel"]],
    ["Y1MS8EindQVtImg1c0", []],
    ["emFuf15efPsBJj1jJY", ["Monica"]],
    ["YrNvBeAj6eWigWZ9y2", ["Chandler"]],
    ["SUDyRKWmZQpk7UEro0", ["Rachel"]],
    ["eIaJ53tgwv7zZgNlZI", ["Joey"]],
    ["cOcpNpYuz0t6KKRO3O", ["Phoebe"]],
    ["hR0mXkCvqeWDqBEtVo", ["Chandler"]],
    ["TjMcpRuqRX4WNCWKeV", ["Chandler"]],
    ["fA1OFzprOfRjteYADG", ["Rachel"]],
    ["J0CJbSi92YEo7zRvih", ["Rachel"]],
    ["mEyRZG3R8UKbTcfdZK", ["Chandler"]],
    ["Q7RPgcCBeIMlca3bwJ", ["Rachel"]],
    ["KCTBU1zeAsfigHEXv0", ["Ross"]],
  ],
  S01E02: [
    ["gIApeHTDn6PA0c4ZhB", ["Ross"]],
    ["XHAIMuXxjlzuwjRo3Y", ["Rachel", "Monica"]],
    ["jp3MWN8oy32VydTtCI", ["Joey"]],
    ["KEAtD4gOkGmjMud1Qa", ["Monica"]],
    ["h3jM4UdYC19MQ1iZOk", []],
    ["RJz2bTWG4FkdIie4J7", ["Rachel", "Ross"]],
    ["SslH10w7VLtGcuEkQf", []],
    ["ejDjDv5k5pWg8ibS1k", ["Rachel", "Ross"]],
    ["Qxwq9z4KKNuAQxqAqY", ["Ross"]],
  ],
  S01E03: [
    ["Kd5n9k5nPzQL4n5aBh", ["Joey"]],
    ["Zds1nYFf3RjnuTT7vO", ["Chandler"]],
    ["kEoe8FvrvXtFrBsu6J", ["Ross", "Chandler", "Joey"]],
    ["VzlXnQqJ5rRwduTyX2", ["Joey"]],
    ["UTjjcX2ZkdDJlWfIS2", ["Rachel"]],
    ["XaMLxETqNsIEYB1Zaz", ["Chandler"]],
    ["Wt0I5MEACAFb4SAOsV", ["Phoebe"]],
    ["ZAwaOHiD6VnDaZ72SU", ["Chandler"]],
    ["kEultQ83nzG6V2m0WT", ["Rachel", "Ross", "Chandler", "Joey"]],
    ["ZY8ztxU0pN8DZZaSgX", ["Chandler"]],
    ["gf6E42cTbz7QLkiMp9", ["Phoebe"]],
    ["L0AeB5SSJtOAqopSlj", ["Chandler"]],
    ["Q5iqYwhkZS2sNsPPCV", ["Rachel", "Phoebe"]],
    ["LpvPGnt0kYXlHL4EpH", ["Rachel", "Phoebe"]],
    ["RKGqDU5hPlMaF7lAjJ", ["Ross", "Chandler", "Joey"]],
  ],
  S01E04: [
    ["UowV82VAW9SPCApzuP", ["Chandler", "Joey"]],
    ["XBcp5KwC2vRQnZJgwN", ["Chandler"]],
    ["QTsXzRkuj4PiRfDzYP", ["Rachel"]],
    ["f7MweeWZ37UCNgy1k7", ["Rachel"]],
    ["j3gcs3Z7CrZ7OZAGG6", ["Rachel"]],
    ["Su6xDHNj4jLean4WLp", ["Rachel"]],
    ["Ii3yO8hIwMBv8EwQOr", ["Rachel"]],
    ["YqQDMNyZVL0ogpkfZw", ["Phoebe"]],
    ["Kzh9WDaXvU5UjVkjCZ", ["Monica"]],
    ["L3R09iszeddT2r1T2w", ["Rachel", "Monica", "Phoebe"]],
    ["eMDrtSnS0ndY5xcIMl", ["Joey"]],
    ["ejyzty6AjKEwkbrZIO", ["Chandler"]],
  ],
  S01E05: [
    ["VFeZQ9f5yqi94gl6RO", ["Chandler"]],
    ["LqCsdRjYGx7UPhnloN", ["Rachel"]],
    ["Kc1gMPc19TNoZdHZoY", ["Ross"]],
    ["Sx9KFEg4bCE2O3XxBh", ["Chandler"]],
    ["gfHPwJxsIT04E4y6uK", ["Chandler"]],
    ["WtgLEWBZc2kC1y62Gn", ["Chandler"]],
    ["fXVYNaXGPcMMkYQb7S", []],
    ["cKnTj36mBUABnfFcvm", []],
    ["RJUpTset9XMphaFJ76", []],
    ["KzVO33kB3WN8TYg0rN", ["Chandler"]],
    ["f4P3dMk56cfEus6b60", []],
    ["UQ0PoEEg8bNZeVc8Ul", ["Chandler"]],
    ["ZZNEU8YumQibteSY4m", ["Rachel", "Ross"]],
    ["LSLG0vpCvF3oOwJvqv", ["Rachel", "Ross"]],
    ["f5S3nLo8j2TlkGLvMp", ["Rachel", "Ross"]],
  ],
  S01E06: [
    ["ZaoA21KIj5okzoMJVV", ["Ross", "Monica", "Joey", "Phoebe"]],
    ["Qub9NF3Kc1NMrSavTq", ["Monica"]],
    ["LPs5pRt1OiaHqgTQoT", ["Phoebe"]],
    ["l1m6q81GMbtTQNxYle", ["Monica"]],
    ["MeDlAyl2m0lhrGRgCm", ["Chandler"]],
    ["YPhgZYXw20qOBUkAtD", ["Rachel"]],
    ["MAiNAPpOXL3defV4xh", ["Joey"]],
    ["RH1ZcnSyNCuV4h59jk", ["Chandler"]],
    ["VbVZwUsyZ8aNEYMwFE", ["Ross", "Chandler"]],
    ["Ph0JDckeYq2imC0vtx", ["Monica"]],
  ],
  S01E07: [
    ["drwQBx2dIjKBnOs7MA", ["Chandler"]],
    ["dCEbjDmzhEygxdjE7P", ["Chandler"]],
    ["dTz8dnQ5rc6IF0fZqI", ["Joey"]],
    ["gEYyg3sHmszZloNRyk", ["Phoebe"]],
    ["j6AWsVpahvvAWQZIVW", ["Rachel", "Ross", "Monica", "Joey", "Phoebe"]],
    ["Vc53ZdwhMIFmuz61RD", ["Chandler"]],
    ["UT57nCi3C68I9v52NX", ["Chandler"]],
    ["IazUww3PfsXepuuTUu", ["Joey"]],
    ["cmOOhvE32aiwn0jVXA", ["Joey"]],
    ["M8zeKCGHIwo57fyLyb", ["Rachel", "Ross", "Monica", "Joey", "Phoebe"]],
    ["kbuh51pyHjqdBAJ6os", ["Chandler"]],
    ["PkpZCqotXbcoqM3gk1", []],
    ["KePUFNCXK07OkpW7e6", []],
    ["WRttHdWQtlWBFTghbx", ["Chandler"]],
    ["Qz5tjQbwIaT5k54qmu", ["Ross"]],
    ["iDs6ARqUIbNKgqL4Co", ["Ross"]],
  ],
  S01E08: [
    ["ZaWP1frDn9JAxjSzmQ", ["Chandler"]],
    ["jtFZWO9VeDNGqxJfG9", ["Chandler"]],
    ["idLzmMlVc3KQOJ6qpS", ["Chandler"]],
    ["ZbTT12JPUXSxnmYueL", ["Ross", "Joey"]],
    ["kG9eawhKAWuEoMNZLa", ["Ross", "Monica"]],
    ["KyNMp6wI8VTbx8pa1o", ["Ross"]],
    ["dwFJVPtMM7zEQV4Tfs", ["Rachel", "Monica", "Chandler", "Joey", "Phoebe"]],
    ["UqwdL2UhWIWhhuEn3N", ["Ross"]],
    ["fSBFck7XvXxb1WZNJy", ["Ross"]],
    ["QVmIhI0hAOXWOjdlWT", ["Rachel", "Ross"]],
    ["da61dXvRULLrFerL1r", ["Rachel", "Ross"]],
    ["hW4iRJRU1rsfXve2Is", ["Rachel", "Ross", "Monica", "Chandler", "Joey", "Phoebe"]],
  ],
  S01E09: [
    ["hv3gm6et6OzwoBADcv", ["Rachel"]],
    ["QZ23SqExXSIp8ly5pX", ["Joey"]],
    ["f4J8neQ16G56cYcpAy", ["Ross"]],
    ["d7NPep2Xx8qAgzKtVq", ["Rachel", "Monica", "Chandler"]],
    ["kGpEskotr7wxEeNArN", ["Ross", "Joey"]],
    ["h8fnSBfRp7k4o65e9G", ["Ross"]],
    ["PlU2rfYYfkqDa6dp4m", ["Ross"]],
    ["mBY9Br59Nq1oCPHvn9", ["Rachel", "Chandler"]],
    ["Kenaq5YK78qy5flMCf", ["Monica"]],
    ["SAIQV6odw5G693EIt2", ["Monica"]],
    ["jS39mz5rixsuCn5ev7", ["Chandler"]],
    ["QyWLZCWbnaBm8vHxOd", ["Monica"]],
    ["LSjJjcLwXdHLFR2BCR", ["Ross"]],
    ["WNiFcnBTo9eaN7pwGM", ["Chandler", "Joey"]],
    ["XgXaEZCeLpH8kSB2IC", ["Phoebe"]],
    ["dwRkXxMWhCQOUTCQiD", ["Rachel"]],
    ["PhaADWHEHWmfYKOU4z", ["Rachel", "Ross", "Monica", "Chandler", "Joey", "Phoebe"]],
    ["jpW1ct3qrYDOr16ydy", ["Rachel", "Ross", "Monica", "Chandler", "Joey", "Phoebe"]],
    ["Q86ySOsoUKl2KUm23o", ["Rachel", "Ross", "Monica", "Chandler", "Joey", "Phoebe"]],
  ],
  S01E10: [
    ["dWNDTnRbDLSil2VeKx", ["Ross"]],
    ["Y3AdCnCOViJWoJU4rB", ["Rachel", "Monica", "Chandler", "Joey"]],
    ["JQotslsBDTIjfq5ncb", ["Joey"]],
    ["jpyxmfrjroIbF76N6s", ["Phoebe"]],
    ["hSFGpAAuz3REzMXrkv", ["Ross", "Monica", "Chandler", "Joey"]],
    ["hvFz0KhnHU6LZ4bapT", ["Rachel", "Joey"]],
    ["j32q2SqWmOCiM2XN01", ["Chandler"]],
    ["dzIjBXapl7Untu2fAb", ["Phoebe"]],
    ["dYs6lSw5zroEombfOF", ["Chandler"]],
    ["Y01HN0ejK4dQnXdzUv", []],
    ["l3mswUrsxXhf3N7fV8", ["Chandler"]],
    ["IbmQvzzgtUVZDfUSQP", ["Chandler"]],
    ["St9taQSB1i8uz9Yy3k", []],
    ["ihNLB1eoKABhg0efDb", ["Chandler"]],
    ["YLsL8J0KyQLsjxWfao", ["Chandler", "Joey"]],
  ],
  S01E11: [
    ["QvpZ7v9lnZvRcNIQi5", ["Monica", "Phoebe"]],
    ["lPF1CyJXXcTZmUrP2J", ["Chandler"]],
    ["Stv65xsI78WCLF6qKh", ["Ross"]],
    ["KEfM3tK8vmJC66EuEJ", ["Monica"]],
    ["H6EhCW73YiyjGMMCgF", ["Ross"]],
    ["iK5B25QkZrzKgfvFQw", ["Ross"]],
    ["eidtow3Zp8DXRxIovD", ["Chandler"]],
    ["XAxT6atAkwYvD2vQtJ", ["Joey"]],
    ["htkLDMetC4PGxkKUpg", ["Joey"]],
    ["hSoqdBi5aTHZ4QFdtT", ["Joey"]],
  ],
  S01E12: [
    ["MZFHPbll4fwlIQwXDO", ["Joey"]],
    ["Qv4uyAPIkKSM3CuocN", ["Monica"]],
    ["eIsV1HuY3nH6BeIgWc", ["Ross"]],
    ["cOiNVODcm5hmOfYKIs", ["Ross"]],
    ["Js8PuZpW2TtS8qChRO", ["Ross"]],
    ["Q81P7wD28DgvnB4oAp", ["Chandler", "Joey"]],
    ["Zb5M7qgVKhnBf398D9", ["Phoebe"]],
    ["H3M9SaO4GKI5nrz3nE", ["Ross", "Monica", "Chandler", "Joey"]],
    ["joxKISS2tgtu1fpHec", ["Rachel", "Phoebe"]],
    ["jowjBv1wXAJfy3zQDd", ["Rachel", "Phoebe"]],
    ["Ti1L8Q9P0Wl2L7iqM3", ["Ross"]],
    ["lSyV3AwDQCTlpy4pFZ", ["Rachel", "Ross"]],
    ["d8iPwdet3gqCdpBBio", ["Chandler", "Joey"]],
  ],
  S01E13: [
    ["VHZaTZby8XYAipJRIE", ["Rachel"]],
    ["W6R58vmWaMUvqJ7VUP", ["Chandler"]],
    ["KdBxqRPqBii9UpNzGw", ["Chandler"]],
    ["llrYRS0vZXJDg8gFjQ", ["Rachel"]],
    ["QWA9p190VpNLxO1ryW", []],
    ["Tj3yKhxT3N7l9vZF5S", ["Rachel"]],
    ["YqW6x1rVpPYpPbOgmO", ["Rachel"]],
    ["QUAZw3tKBW8UlzzHg0", ["Chandler", "Joey"]],
    ["dYl0y1a58nndpaMKZb", ["Rachel", "Joey"]],
    ["f5LxYIuuc9MKJAEB9E", ["Phoebe"]],
    ["QUFYBQsqKXJeLeMzp7", ["Phoebe"]],
  ],
  S01E14: [
    ["YlXhnFLRStBOU41sDV", ["Chandler", "Joey"]],
    ["dsQxkhglEIYvAMBWTY", ["Chandler"]],
    ["IeiK6lFEQs6xSDagx6", ["Chandler", "Joey"]],
    ["ejD28dM6BW7RsWKBNt", ["Phoebe"]],
    ["gGl6ZLaaJN38aJlknQ", ["Chandler"]],
    ["lrOZG0Xb00ylcc9JW8", []],
    ["ZYLH4smh84EM42yrBj", ["Chandler"]],
    ["U6MbDAj3qhE5jJYXxB", ["Chandler"]],
    ["LOzsr2UfSfFr9DIuWS", ["Chandler"]],
    ["kBxZkwHcMGtzs6mFo7", ["Rachel", "Monica", "Phoebe"]],
    ["XBQwFWwss5pE6rO99i", ["Rachel", "Monica", "Phoebe"]],
    ["Q7R6t0CX1jI1UAgToY", ["Chandler"]],
    ["PiuLGNQPBzgQXuneyD", ["Joey"]],
    ["kgmT1MgYzKqLOK388g", []],
    ["fqtGE1bka9nXRmZ1ke", ["Chandler"]],
  ],
  S01E15: [
    ["J4spUDN15DmMS0BMot", ["Monica", "Phoebe"]],
    ["kg6XIldTccUHcgGG0q", []],
    ["RKZM8opDnuuC4OkFU5", ["Chandler"]],
    ["YOTCDK8zhWdDMLhE7Q", ["Joey"]],
    ["WoLwsd42kAeyBl29Qj", ["Chandler"]],
    ["Tf9XNuQXOcu95mZyCU", []],
    ["LRy5oHUv67jsUK0gH7", ["Phoebe"]],
    ["fYk8CwTypjPArDbRTn", ["Monica"]],
    ["ftpwA46n5E67rRhWnY", []],
    ["Yksn7fmG1fi6jKO1sA", []],
    ["jR4p5oRNxG7sSLmKgb", ["Monica"]],
    ["WqWvIK0cWI0UmEVFDU", ["Rachel"]],
    ["f5LUvHRcjnV0yYO1An", []],
    ["LpXv1ued8OfuS9SKXk", ["Chandler"]],
    ["f6Jv92MQREQ3yvo4bm", ["Chandler"]],
  ],
  S01E16: [
    ["hTZkWwuyHSOQTDX3mN", ["Monica", "Phoebe"]],
    ["QAUAYUX7URRBgIUeAG", ["Ross"]],
    ["hWuuOpIrNVy1J07awt", ["Ross"]],
    ["TJgw1eBccerU3FdMwh", ["Ross"]],
    ["XEPUycoXoKn3laDjgf", []],
    ["MDxCXWYiwbvTru9ADJ", []],
    ["ftYlTLEHXtiB19Y6oy", []],
    ["ckBCs9EPM9rN6WSe06", []],
    ["LQoLJ0qSnzDp3ETX0t", ["Ross"]],
    ["kz1G2oijlyFhKMFeh9", ["Phoebe"]],
    ["KGx6SCExbxlBwEtGiI", ["Phoebe"]],
    ["VbhkwLroHBrgRQJ25n", ["Rachel"]],
  ],
  S01E17: [
    ["RMeTXWQvYoQ2wSfHIQ", ["Ross", "Chandler", "Joey"]],
    ["hVlZjLqpk31OxmkoTS", ["Monica"]],
    ["hrcYhsqSfzBmwaay8H", ["Ross"]],
    ["frBakvqDuXYJQzgDDb", ["Rachel", "Ross", "Monica"]],
    ["kyKDOqpFsNmoNTwEWu", ["Phoebe"]],
    ["Q59MqYVGwnOwiKIRNA", ["Ross"]],
    ["J2BwCnMId4eE9UIYfM", ["Rachel"]],
    ["LOR68hhP3nAn2zYX5c", ["Rachel", "Ross", "Monica", "Chandler"]],
    ["Kau9HDsfOQClgQLjWV", ["Joey"]],
    ["J1QhznbZgBUcxif5NT", ["Joey", "Phoebe"]],
    ["ghN8V00a0NkK0rLsIh", []],
  ],
  S01E18: [
    ["UQOH9G2ZiNwLQ3pwJw", ["Rachel", "Ross", "Monica", "Chandler", "Joey", "Phoebe"]],
    ["XGOKnMCcsmH2WdLR4p", ["Ross", "Chandler"]],
    ["XcjZmyziQD1W8dnbIB", ["Rachel"]],
    ["kfuaTjyVDUw7oL8v9T", ["Rachel", "Phoebe"]],
    ["SY4DtNDUcTnwTEHAg5", ["Rachel"]],
    ["WrscggGmRDGHS4WACb", ["Rachel"]],
    ["YN7kUjeF4wwLNAnE9Q", ["Rachel", "Ross", "Monica", "Chandler", "Joey", "Phoebe"]],
    ["VgrHrELzIGU3Zc3nv5", ["Joey"]],
    ["U3U3Sa86U04jVAnRdN", ["Rachel", "Monica", "Phoebe"]],
    ["KZRnLNMBJ7Q0RxkhPf", ["Rachel"]],
    ["ggWA5i5Sn8X7hsPehy", ["Ross", "Chandler", "Joey"]],
  ],
  S01E19: [
    ["ej6aBrh3ePRkEI5U5P", ["Rachel"]],
    ["hW9z0MY9WqdDDMLczM", ["Rachel", "Ross"]],
    ["W0DeTj7UVPGnPGRawL", ["Rachel", "Chandler", "Joey"]],
    ["cKKDPjyWiAJWZ4ewDK", ["Monica", "Phoebe"]],
    ["gg3ag83bWBPHt3l55O", ["Rachel", "Ross"]],
    ["JQAYsaeQvqkQbS0fJq", ["Rachel"]],
    ["ZcKpuU9eIONa5HOoed", ["Rachel"]],
    ["UttuZjWsrDIhtQiUnO", ["Monica", "Phoebe"]],
    ["XG7Gm21mjUAR0ennR5", ["Monica", "Phoebe"]],
    ["XzkXziN2i8SQ1w8Fq9", []],
    ["lr7UJ1hVrrYbTeukO5", ["Rachel", "Ross"]],
  ],
  S01E20: [
    ["l0EgOCMf83RGNRJucg", ["Ross"]],
    ["McnBRPzHmMJ1QrbuT0", ["Phoebe"]],
    ["XGaUVLlrTX5kXYbz0o", ["Chandler", "Phoebe"]],
    ["YN7Hwsn2LN5ZMPDMzh", ["Chandler"]],
    ["SVMs8E3SDROD5mOD6H", ["Rachel"]],
    ["fA81FF4mdE6lgeoJwb", ["Chandler"]],
    ["mBvlesAuKzhWfh1Fmt", ["Rachel"]],
    ["j6kui29ur8LVuBsTct", ["Chandler"]],
    ["Y4PW1su4N0DoZWlcC2", ["Rachel"]],
  ],
  S01E21: [
    ["iF7fbf1y1SpoPRtlHQ", ["Rachel"]],
    ["Tfvrs5cUcxbAPsUbzl", ["Chandler", "Joey"]],
    ["icUsWOSpxjUqECRmwu", ["Chandler", "Joey"]],
    ["KxhMgiklWomI1iUpFU", ["Phoebe"]],
    ["LSKHb1ZXHfjbKVkHst", ["Phoebe"]],
    ["kcerH6iby9Id8KRTHr", ["Ross", "Chandler", "Joey"]],
    ["lpseLOknwe5EWEHYcM", ["Ross"]],
    ["kcaPuGBLcoaHfcNz3o", ["Chandler"]],
    ["lp6deU21ixSR5304Be", ["Monica"]],
    ["gdwJXQlEOfiuNnxMjP", ["Monica"]],
    ["jqSMru5RvdSJiAM6MS", ["Monica"]],
    ["efmOVHW1Y168tyEKwJ", ["Monica"]],
    ["TiaqGy1zcjhAoIltD8", ["Monica"]],
  ],
  S01E22: [
    ["kcqfdKcwoEHokiYAP4", ["Chandler"]],
    ["VeTHMwQ1d1hygOhfKi", ["Chandler"]],
    ["gIfmJ1yfNE1CM2vIJl", ["Ross", "Joey", "Phoebe"]],
    ["fUSoUQId6eoB0SwbVC", []],
    ["lrhZTrRl0HEkb6AIXz", ["Monica"]],
    ["L3QSsZmINxHAR4st7T", ["Joey"]],
    ["H7AceDqkppfRrpmY7L", ["Phoebe"]],
    ["ihGB4JRrJFRNbdYomi", ["Phoebe"]],
    ["f6zcJssQkdT4VQ7dIF", ["Ross"]],
    ["hWYAAK6XgxAxso2hZh", ["Ross"]],
  ],
  S01E23: [
    ["IcvONJqdYXRvqeT1S4", ["Rachel", "Joey"]],
    ["RLoKb5Q8DV7z98Rm6S", ["Phoebe"]],
    ["McCKfbq2cn5DDMs92s", ["Rachel"]],
    ["MbFTlm7S6pPEcI0dHo", ["Monica", "Chandler"]],
    ["McUwVAbwqTQtgVqiYn", ["Phoebe"]],
    ["fX7YYQW6r2DIwoYqME", ["Joey"]],
    ["lmuWztVhcg753ERV1X", ["Ross"]],
    ["H1jvPs6UFJLL4Yf6Oy", ["Ross"]],
    ["S3z3LmdyL7xGE9JvZc", ["Ross"]],
    ["ieJhqWk0LcNqbE2dTj", ["Rachel", "Ross", "Monica", "Chandler", "Joey", "Phoebe"]],
  ],
  S01E24: [
    ["VeYP8K849DFKGmkIuS", ["Chandler", "Joey"]],
    ["llgjxiHhLt1LBwyD4e", ["Chandler"]],
    ["fsEMLq95wCLVyrdXmh", ["Phoebe"]],
    ["ibp86AVBdsX12HwB9K", ["Joey"]],
    ["hTD4YckW1EQ5m8zkxs", ["Chandler"]],
    ["WpaVhEcp3Qo2TjwyI1", ["Chandler"]],
    ["Vi0BBokMIG5AjTN5l5", ["Chandler"]],
    ["fvYR60mQCKt2x9hV3y", ["Joey"]],
    ["QAsspCntzBzsnTaPeQ", ["Rachel"]],
    ["SUnxtljzCdbjojnxS3", ["Rachel"]],
  ],
};
